## Table of Contents
## 1. Importing Libraries and Data
## 2. Data Wrangling
#### 2.1. BR - Brazil
#### 2.2. EUN - Europe Nordic & East
#### 2.3. EUW -  Europe West
#### 2.4. KR - Korea
#### 2.5. LAN - Latin America North
#### 2.6. LAS - Latin America South
#### 2.7. NA - North America
#### 2.8. OC - Oceania
#### 2.9. RU - Russia
#### 2.10. TR - Turkey
## 3. Statistical Analysis
#### 3.1. BR Match Data
#### 3.2. EUN Match Data
#### 3.3. EUW Match Data
#### 3.4. KR Match Data
#### 3.5. LAN Match Data
#### 3.6. LAS Match Data
#### 3.7. NA Match Data
#### 3.8. OC Match Data
#### 3.9. RU Match Data
#### 3.10. TR Match Data
## 4. Exporting

# 1. Importing Libraries and Data

In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Importing Data
# Quite a bit of different sets
path = r'C:\Users\javir\Downloads\Javis Data Analytics stuff\Achievement 6\LoL Regional Project'
BR = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataBr1.csv'))
EUN = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataEun1.csv'))
EUW = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataEuw1.csv'))
KR = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataKR.csv'))
LAN = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataLa1.csv'))
LAS = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataLa2.csv'))
NA = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataNa1.csv'))
OC = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataOc1.csv'))
RU = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataRu.csv'))
TR = pd.read_csv(os.path.join(path,'02 Data','Original Data','MatchDataTr1.csv'))

In [3]:
# We have 49 columns, we need to be able to see all of them
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

We have 10 different csv files for our data, which isn't ideal, we will be merging our data after analyzing each region seperately.

# 2. Data Wrangling

### Since we have 10 different regions we will clean them in sections

## 2.1. BR - Brazil

In [4]:
# Checking our shape
BR.shape

(40000, 49)

In [5]:
# Checking our data types
BR.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [6]:
# Checking for duplicated rows
BR_Dups = BR.duplicated()

In [7]:
# Flase records match count, indicating no dupplicates
BR_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

In [8]:
# Checking for missing values
BR.isnull().sum()

matchId            0
seasonId           0
gameDuration       0
gameCreation       0
win                0
team               0
wardsPlaced        0
firstBlood         0
firstTower         0
firstInhibitor     0
firstDragon        0
firstRiftHerald    0
firstBaron         0
teamKills          0
towerKills         0
inhibitorKills     0
dragonKills        0
riftHeraldKills    0
baronKills         0
ban1               0
ban2               0
ban3               0
ban4               0
ban5               0
pick1              0
pick2              0
pick3              0
pick4              0
pick5              0
player1Kills       0
player2Kills       0
player3Kills       0
player4Kills       0
player5Kills       0
spell1Player1      0
spell1Player2      0
spell1Player3      0
spell1Player4      0
spell1Player5      0
spell2Player1      0
spell2Player2      0
spell2Player3      0
spell2Player4      0
spell2Player5      0
soloKills          0
duoKills           0
trioKills          0
quadKills    

#### All looks good no missing values right? Actually, during draft phase it is possible to Not Ban a champion, so lets check for those values

In [9]:
BR['ban1'].value_counts()

Akali           3608
Camille         2682
Yasuo           2351
Talon           2090
Aatrox          1588
Morgana         1563
Zoe             1526
Irelia          1479
Graves          1417
Pyke            1368
Leblanc         1354
                1213
Evelynn          876
Fiora            821
Kaisa            804
Darius           766
Taliyah          732
Vladimir         721
Rammus           646
Rakan            641
Zed              526
Riven            500
Jax              487
AurelionSol      463
Karthus          416
Alistar          401
Lucian           391
Fiddlesticks     382
Urgot            382
Gangplank        332
Shaco            309
XinZhao          307
Quinn            300
Ahri             286
Draven           285
Kindred          285
Kassadin         274
Braum            266
Khazix           245
Kled             234
LeeSin           195
Lulu             184
Thresh           179
Nunu             168
Nocturne         164
Rengar           164
Ezreal           164
Fizz         

Well we can see 1,213 counts of '___'. It's just bank, which inicates No Ban, now we could leave this blank as it's not considered a missing value, but it's not very helpful for someone else to inspect and notice just nothing and not know. So we will change Blanks during ban phase into 'No Ban'

In [10]:
BR['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [11]:
BR['ban1'].value_counts()

Akali           3608
Camille         2682
Yasuo           2351
Talon           2090
Aatrox          1588
Morgana         1563
Zoe             1526
Irelia          1479
Graves          1417
Pyke            1368
Leblanc         1354
No Ban          1213
Evelynn          876
Fiora            821
Kaisa            804
Darius           766
Taliyah          732
Vladimir         721
Rammus           646
Rakan            641
Zed              526
Riven            500
Jax              487
AurelionSol      463
Karthus          416
Alistar          401
Lucian           391
Fiddlesticks     382
Urgot            382
Gangplank        332
Shaco            309
XinZhao          307
Quinn            300
Ahri             286
Draven           285
Kindred          285
Kassadin         274
Braum            266
Khazix           245
Kled             234
LeeSin           195
Lulu             184
Thresh           179
Nunu             168
Nocturne         164
Rengar           164
Ezreal           164
Fizz         

Now we have 1,213 'No Ban' counts, now we have to do the same to 'ban2' 'ban3' 'ban4' 'ban5'

In [12]:
BR['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [13]:
BR['ban2'].value_counts()

Akali           3551
Camille         2662
Yasuo           2383
Talon           2055
Zoe             1569
Morgana         1530
Graves          1509
Aatrox          1505
Pyke            1459
Irelia          1427
Leblanc         1360
No Ban          1257
Evelynn          885
Kaisa            830
Darius           783
Fiora            770
Vladimir         730
Taliyah          708
Rammus           660
Rakan            621
Zed              562
Riven            485
AurelionSol      484
Jax              442
Alistar          418
Karthus          393
Lucian           383
Urgot            376
Gangplank        340
Fiddlesticks     328
Khazix           327
XinZhao          305
Kindred          289
Kled             278
Draven           270
Ahri             268
Shaco            265
Quinn            250
Kassadin         248
Braum            240
LeeSin           222
Lulu             206
Nunu             194
Thresh           188
Fizz             167
Nocturne         153
Rengar           149
Trundle      

In [14]:
BR['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [15]:
BR['ban3'].value_counts()

Akali           3562
Camille         2737
Yasuo           2399
Talon           2081
Aatrox          1541
Zoe             1528
Irelia          1467
Graves          1453
Morgana         1440
Pyke            1378
Leblanc         1355
No Ban          1287
Evelynn          892
Vladimir         812
Kaisa            807
Fiora            802
Darius           754
Taliyah          709
Rammus           651
Rakan            620
Zed              563
AurelionSol      489
Riven            482
Lucian           429
Jax              419
Alistar          404
Karthus          398
Urgot            395
Fiddlesticks     371
Gangplank        369
Shaco            310
Ahri             309
Kindred          290
Draven           282
XinZhao          279
Quinn            274
Khazix           272
Kled             269
Braum            252
Kassadin         236
LeeSin           213
Thresh           212
Lulu             187
Fizz             180
Nunu             180
Nocturne         171
Rengar           149
Singed       

In [16]:
BR['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [17]:
BR['ban4'].value_counts()

Akali           3494
Camille         2784
Yasuo           2471
Talon           2016
Zoe             1600
Aatrox          1521
Graves          1477
Irelia          1471
Morgana         1468
Pyke            1434
Leblanc         1392
No Ban          1357
Evelynn          852
Kaisa            821
Vladimir         781
Darius           752
Fiora            750
Taliyah          743
Rammus           589
Rakan            586
Zed              549
Riven            504
AurelionSol      478
Jax              421
Lucian           409
Alistar          403
Urgot            399
Karthus          367
Fiddlesticks     353
Gangplank        325
XinZhao          315
Draven           302
Khazix           290
Quinn            288
Ahri             287
Kindred          285
Shaco            284
Braum            265
Kassadin         257
Kled             231
LeeSin           230
Thresh           192
Lulu             182
Nunu             180
Rengar           171
Fizz             160
Nocturne         158
Trundle      

In [18]:
BR['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [19]:
BR['ban5'].value_counts()

Akali           3592
Camille         2777
Yasuo           2477
Talon           2072
Zoe             1606
Graves          1498
Aatrox          1484
Irelia          1478
Morgana         1434
Pyke            1398
Leblanc         1380
No Ban          1293
Evelynn          871
Kaisa            834
Darius           778
Vladimir         766
Taliyah          737
Fiora            719
Rammus           601
Rakan            588
Zed              554
AurelionSol      495
Riven            478
Jax              440
Urgot            432
Alistar          421
Lucian           420
Karthus          393
Fiddlesticks     354
Gangplank        328
Shaco            317
Ahri             315
Draven           311
XinZhao          288
Kindred          288
Braum            282
Quinn            264
Kled             264
Khazix           260
LeeSin           219
Kassadin         213
Lulu             178
Thresh           175
Nunu             168
Rengar           161
Nocturne         146
Singed           143
Ezreal       

#### Everything seems to have functioned as intended

In [20]:
# Checking values to see if anything is out of the ordinary
BR.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0  40000.000000  40000.000000  40000.000000   
mean   1.453752e+09      11.0   1618.141050      0.500000      0.500000   
std    2.319282e+07       0.0    448.081153      0.500006      0.500006   
min    1.293655e+09      11.0    190.000000      0.000000      0.000000   
25%    1.445629e+09      11.0   1375.000000      0.000000      0.000000   
50%    1.458729e+09      11.0   1625.000000      0.500000      0.500000   
75%    1.470401e+09      11.0   1898.000000      1.000000      1.000000   
max    1.478753e+09      11.0   3347.000000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000     40000.00000  40000.000000   
mean      58.241000      0.497650      0.487275         0.44435      0.474925   
std       30.169438      0.500001      0.499844         0.49690      0.499377   
min        0.000000      0.000000      0.000000         0.00000      0.000000   
25%       39.000000      0.000000      0.000000         0.00000      0.000000   
50%       53.000000      0.000000      0.000000         0.00000      0.000000   
75%       71.000000      1.000000      1.000000         1.00000      1.000000   
max      404.000000      1.000000      1.000000         1.00000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.418950      0.345425     23.433000      5.443975   
std           0.493393      0.475513     10.805273      3.750722   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     16.000000      2.000000   
50%           0.000000      0.000000     23.000000      6.000000   
75%           1.000000      1.000000     30.000000      9.000000   
max           1.000000      1.000000     77.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.885900      1.265600         0.418950      0.433425   
std          1.117928      1.123382         0.493393      0.597392   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          0.000000      1.000000         0.000000      0.000000   
75%          2.000000      2.000000         1.000000      1.000000   
max         10.000000      6.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.649150      5.158775      5.216625      5.184025      5.224425   
std        3.807416      4.012339      4.068957      4.041648      4.077852   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      4.000000      4.000000      4.000000      4.000000   
75%        4.000000      7.000000      7.000000      7.000000      8.000000   
max       30.000000     34.000000     30.000000     30.000000     29.000000   

          soloKills      duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       5.072975      9.387825      7.271150      3.441550      0.858100  
std        3.331550      4.850135      4.227981      2.904857      1.350578  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        3.000000      6.000000      4.000000      1.000000      0.000000  
50%        5.000000      9.000000      7.000000      3.000000      0.000000  
75%        7.000000     12.000000     10.000000      5.000000      1.000000  
max       25.000000     36

In [21]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
BR.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  1464336847        11          1278  <1536777218683    0     1           34   
1  1464336847        11          1278  <1536777218683    1     0           50   
2  1469537223        11          1689  <1537133828880    0     1           45   
3  1469537223        11          1689  <1537133828880    1     0          102   
4  1476908929        11          1503  <1537913707045    1     1           31   
5  1476908929        11          1503  <1537913707045    0     0           39   
6  1449052030        11          2293  <1534713343464    0     1           78   
7  1449052030        11          2293  <1534713343464    1     0           78   
8  1474926897        11          1600  <1537684573576    0     1           45   
9  1474926897        11          1600  <1537684573576    1     0           42   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           0               0            0                0   
1           1           1               0            1                1   
2           0           0               0            0                0   
3           1           1               1            1                1   
4           1           1               1            1                1   
5           0           0               0            0                0   
6           1           0               1            0                0   
7           0           1               0            1                1   
8           0           0               0            1                1   
9           1           1               1            0                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0          9           1               0            0   
1           1         15           3               0            2   
2           0         14           5               0            1   
3           1         31           7               1            2   
4           1         31          10               3            3   
5           0         19           0               0            0   
6           1         28           7               3            2   
7           0         42           9               1            2   
8           0          8           3               0            2   
9           1         23          11               3            1   

   riftHeraldKills  baronKills      ban1     ban2       ban3      ban4  \
0                0           0   Camille  Alistar    Leblanc     Talon   
1                1           1  Kassadin    Talon      Yasuo     Akali   
2                0           0    Aatrox     Nami    Camille      Pyke   
3                1           1    Graves  Morgana      Talon  Vladimir   
4                1           1   Evelynn    Akali     Singed  Vladimir   
5                0           0     Akali   Graves  TahmKench   Taliyah   
6                0           1      Jhin   Singed        Zoe     Akali   
7                1           1  Vladimir      Zoe     Gragas     Akali   
8                1           0   Morgana    Akali    XinZhao     Yasuo   
9                0           1       Zoe  Leblanc    Morgana     Kaisa   

      ban5     pick1    pick2         pick3    pick4     pick5  player1Kills  \
0    Rakan    Irelia  Morgana  Fiddlesticks   Kennen     Vayne             0   
1  Camille     Kaisa   Darius        Thresh   LeeSin  Vladimir             1   
2    Akali    Irelia    Kaisa           Jax   Thresh   Taliyah             0   
3  Leblanc     Urgot     Lulu        Lucian     Kayn     Yasuo            12   
4   Graves    LeeSin      Zed        Draven  Alistar    Rumble             1   
5  Camille    Irelia    Urgot         Janna   Gragas     Kaisa             5   
6    Rakan     Riven  Morgana       Leblanc   Soraka     Kaisa             1   
7    Varus     Braum   Lucian        Graves    Talon      Sion           

As mentioned in our project document, the Spell column had an error transfering data, duplicating the results of 'spell1PlayerX' to 'spell2Playerx', this makes the data uninformative and incorrect and not usable for any analysis we are looking to perform. So for all regions these columns will have to be removed.

In [22]:
# Creating our cleaned data frame
BR_Clean = BR.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [23]:
# Checking our shape for consistent row count and to ensure columns have been removed
BR_Clean.shape

(40000, 39)

In [24]:
BR_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  1464336847        11          1278  <1536777218683    0     1           34   
1  1464336847        11          1278  <1536777218683    1     0           50   
2  1469537223        11          1689  <1537133828880    0     1           45   
3  1469537223        11          1689  <1537133828880    1     0          102   
4  1476908929        11          1503  <1537913707045    1     1           31   
5  1476908929        11          1503  <1537913707045    0     0           39   
6  1449052030        11          2293  <1534713343464    0     1           78   
7  1449052030        11          2293  <1534713343464    1     0           78   
8  1474926897        11          1600  <1537684573576    0     1           45   
9  1474926897        11          1600  <1537684573576    1     0           42   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           0               0            0                0   
1           1           1               0            1                1   
2           0           0               0            0                0   
3           1           1               1            1                1   
4           1           1               1            1                1   
5           0           0               0            0                0   
6           1           0               1            0                0   
7           0           1               0            1                1   
8           0           0               0            1                1   
9           1           1               1            0                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0          9           1               0            0   
1           1         15           3               0            2   
2           0         14           5               0            1   
3           1         31           7               1            2   
4           1         31          10               3            3   
5           0         19           0               0            0   
6           1         28           7               3            2   
7           0         42           9               1            2   
8           0          8           3               0            2   
9           1         23          11               3            1   

   riftHeraldKills  baronKills      ban1     ban2       ban3      ban4  \
0                0           0   Camille  Alistar    Leblanc     Talon   
1                1           1  Kassadin    Talon      Yasuo     Akali   
2                0           0    Aatrox     Nami    Camille      Pyke   
3                1           1    Graves  Morgana      Talon  Vladimir   
4                1           1   Evelynn    Akali     Singed  Vladimir   
5                0           0     Akali   Graves  TahmKench   Taliyah   
6                0           1      Jhin   Singed        Zoe     Akali   
7                1           1  Vladimir      Zoe     Gragas     Akali   
8                1           0   Morgana    Akali    XinZhao     Yasuo   
9                0           1       Zoe  Leblanc    Morgana     Kaisa   

      ban5     pick1    pick2         pick3    pick4     pick5  player1Kills  \
0    Rakan    Irelia  Morgana  Fiddlesticks   Kennen     Vayne             0   
1  Camille     Kaisa   Darius        Thresh   LeeSin  Vladimir             1   
2    Akali    Irelia    Kaisa           Jax   Thresh   Taliyah             0   
3  Leblanc     Urgot     Lulu        Lucian     Kayn     Yasuo            12   
4   Graves    LeeSin      Zed        Draven  Alistar    Rumble             1   
5  Camille    Irelia    Urgot         Janna   Gragas     Kaisa             5   
6    Rakan     Riven  Morgana       Leblanc   Soraka     Kaisa             1   
7    Varus     Braum   Lucian        Graves    Talon      Sion           

## 2.2. EUN - Europe Nordic & East

In [25]:
# Checking our shape
EUN.shape

(40000, 49)

In [26]:
# Checking our data types
EUN.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [27]:
# Checking for duplicated rows
EUN_Dups = EUN.duplicated()

In [28]:
# Flase records match count, indicating no dupplicates
EUN_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [29]:
EUN['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [30]:
EUN['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [31]:
EUN['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [32]:
EUN['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [33]:
EUN['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [34]:
# Checking 1 columns counts to ensure it worked
EUN['ban1'].value_counts()

Draven          2487
Akali           2456
Evelynn         1746
Yasuo           1728
Irelia          1589
Morgana         1508
Graves          1496
Vladimir        1479
Darius          1417
Zoe             1242
Rengar          1131
Jax             1128
Zed             1041
Aatrox          1036
Pyke            1006
Kaisa            990
Talon            893
Camille          888
Tryndamere       792
Leblanc          791
Fiddlesticks     624
Kassadin         592
Khazix           591
Kindred          527
Taliyah          496
Nocturne         456
XinZhao          451
Katarina         443
Fizz             403
Shaco            401
No Ban           393
Quinn            372
Fiora            304
Lucian           292
Heimerdinger     281
Lulu             267
Rakan            253
Jhin             237
MasterYi         223
Warwick          210
Brand            202
Poppy            192
Hecarim          176
Thresh           166
Braum            164
Trundle          147
Riven            143
Swain        

Worked as intended, 393 'No Ban' records

In [35]:
# Checking values to see if anything is out of the ordinary
EUN.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0  40000.000000  40000.000000  40000.000000   
mean   2.017082e+09      11.0   1594.112350      0.500000      0.500000   
std    2.425318e+07       0.0    432.684087      0.500006      0.500006   
min    1.889650e+09      11.0    190.000000      0.000000      0.000000   
25%    2.004887e+09      11.0   1347.000000      0.000000      0.000000   
50%    2.022097e+09      11.0   1594.500000      0.500000      0.500000   
75%    2.034508e+09      11.0   1861.000000      1.000000      1.000000   
max    2.046998e+09      11.0   3707.000000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000    40000.000000  40000.000000   
mean      53.438700      0.498125      0.491325        0.451375      0.476475   
std       30.125272      0.500003      0.499931        0.497636      0.499453   
min        0.000000      0.000000      0.000000        0.000000      0.000000   
25%       35.000000      0.000000      0.000000        0.000000      0.000000   
50%       47.000000      0.000000      0.000000        0.000000      0.000000   
75%       65.000000      1.000000      1.000000        1.000000      1.000000   
max      477.000000      1.000000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.371775      0.332750     23.726325      5.357350   
std           0.483285      0.471204     11.049397      3.746619   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     16.000000      2.000000   
50%           0.000000      0.000000     23.000000      6.000000   
75%           1.000000      1.000000     31.000000      9.000000   
max           1.000000      1.000000     78.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.869050      1.229075         0.371775      0.413825   
std          1.091619      1.113252         0.483285      0.588798   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          0.000000      1.000000         0.000000      0.000000   
75%          1.000000      2.000000         1.000000      1.000000   
max         11.000000      6.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.672425      5.239250      5.277325      5.259400      5.277925   
std        3.864349      4.118165      4.150198      4.151824      4.161534   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      4.000000      4.000000      4.000000      4.000000   
75%        4.000000      7.000000      8.000000      8.000000      8.000000   
max       29.000000     41.000000     33.000000     32.000000     30.000000   

          soloKills      duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       5.555200      9.679650      7.014850      3.239200      0.830425  
std        3.566577      4.993791      4.177788      2.866084      1.350098  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        3.000000      6.000000      4.000000      1.000000      0.000000  
50%        5.000000      9.000000      7.000000      3.000000      0.000000  
75%        8.000000     13.000000     10.000000      5.000000      1.000000  
max       31.000000     39

In [36]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
EUN.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  2041817028        11          1835  <1537455021443    1     1           42   
1  2041817028        11          1835  <1537455021443    0     0           58   
2  2004392497        11          1466  <1532016961096    0     1           33   
3  2004392497        11          1466  <1532016961096    1     0           93   
4  1956086048        11          1255  <1524910704672    1     1           35   
5  1956086048        11          1255  <1524910704672    0     0           41   
6  1987458160        11          1746  <1529608527950    1     1           90   
7  1987458160        11          1746  <1529608527950    0     0          115   
8  2025037238        11          2354  <1535193335267    1     1          102   
9  2025037238        11          2354  <1535193335267    0     0           95   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           0               1            0                0   
1           1           1               0            1                0   
2           0           0               0            0                0   
3           1           1               1            1                1   
4           0           1               1            1                1   
5           1           0               0            0                0   
6           1           1               1            0                0   
7           0           0               0            1                1   
8           0           0               1            0                0   
9           1           1               0            1                1   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0         25           7               1            0   
1           1         36           3               0            3   
2           0          6           0               0            0   
3           1         19           9               2            2   
4           0         11          10               3            2   
5           0         16           0               0            0   
6           1         20          10               2            2   
7           0         26           2               0            1   
8           1         24           8               2            0   
9           0         30           5               0            3   

   riftHeraldKills  baronKills      ban1        ban2          ban3  \
0                0           0    Darius       Yasuo        Irelia   
1                0           1  Vladimir        Kayn       Morgana   
2                0           0       Zed      Draven  Fiddlesticks   
3                1           1       Zoe  Tryndamere      Nocturne   
4                1           0    Khazix      Rengar        Darius   
5                0           0     Xayah      Darius        Khazix   
6                0           1    Darius     Taliyah        Irelia   
7                1           0  Vladimir       Talon        Irelia   
8                0           1   Orianna     Morgana        Draven   
9                1           0       Jax      Darius       Camille   

         ban4      ban5        pick1    pick2    pick3     pick4        pick5  \
0     Morgana     Akali      Trundle  Alistar     Ryze     Kaisa  TwistedFate   
1     Camille   Warwick      Evelynn    Brand     Pyke    Lucian      Chogath   
2     Camille   Morgana         Jinx   Thresh   Graves  Vladimir     Katarina   
3     Evelynn     Talon  TwistedFate    Rakan  XinZhao      Shen        Xayah   
4       Xayah      Lulu        Janna  Caitlyn      Jax   Leblanc      Kindred   
5       Shaco     Kaisa        Karma     Olaf     Ryze      Jinx    Gangplank   
6     Leblanc     Yasuo        Jayce   Draven     Bard      Ekko      Nidalee   
7  Tryndamere  Katarina       LeeSin     Fizz    Karma   Camille       Lucian   
8        Sion      Nami     

In [37]:
# Creating our cleaned data frame
EUN_Clean = EUN.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [38]:
# Checking our shape for consistent row count and to ensure columns have been removed
EUN_Clean.shape

(40000, 39)

In [39]:
EUN_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  2041817028        11          1835  <1537455021443    1     1           42   
1  2041817028        11          1835  <1537455021443    0     0           58   
2  2004392497        11          1466  <1532016961096    0     1           33   
3  2004392497        11          1466  <1532016961096    1     0           93   
4  1956086048        11          1255  <1524910704672    1     1           35   
5  1956086048        11          1255  <1524910704672    0     0           41   
6  1987458160        11          1746  <1529608527950    1     1           90   
7  1987458160        11          1746  <1529608527950    0     0          115   
8  2025037238        11          2354  <1535193335267    1     1          102   
9  2025037238        11          2354  <1535193335267    0     0           95   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           0               1            0                0   
1           1           1               0            1                0   
2           0           0               0            0                0   
3           1           1               1            1                1   
4           0           1               1            1                1   
5           1           0               0            0                0   
6           1           1               1            0                0   
7           0           0               0            1                1   
8           0           0               1            0                0   
9           1           1               0            1                1   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0         25           7               1            0   
1           1         36           3               0            3   
2           0          6           0               0            0   
3           1         19           9               2            2   
4           0         11          10               3            2   
5           0         16           0               0            0   
6           1         20          10               2            2   
7           0         26           2               0            1   
8           1         24           8               2            0   
9           0         30           5               0            3   

   riftHeraldKills  baronKills      ban1        ban2          ban3  \
0                0           0    Darius       Yasuo        Irelia   
1                0           1  Vladimir        Kayn       Morgana   
2                0           0       Zed      Draven  Fiddlesticks   
3                1           1       Zoe  Tryndamere      Nocturne   
4                1           0    Khazix      Rengar        Darius   
5                0           0     Xayah      Darius        Khazix   
6                0           1    Darius     Taliyah        Irelia   
7                1           0  Vladimir       Talon        Irelia   
8                0           1   Orianna     Morgana        Draven   
9                1           0       Jax      Darius       Camille   

         ban4      ban5        pick1    pick2    pick3     pick4        pick5  \
0     Morgana     Akali      Trundle  Alistar     Ryze     Kaisa  TwistedFate   
1     Camille   Warwick      Evelynn    Brand     Pyke    Lucian      Chogath   
2     Camille   Morgana         Jinx   Thresh   Graves  Vladimir     Katarina   
3     Evelynn     Talon  TwistedFate    Rakan  XinZhao      Shen        Xayah   
4       Xayah      Lulu        Janna  Caitlyn      Jax   Leblanc      Kindred   
5       Shaco     Kaisa        Karma     Olaf     Ryze      Jinx    Gangplank   
6     Leblanc     Yasuo        Jayce   Draven     Bard      Ekko      Nidalee   
7  Tryndamere  Katarina       LeeSin     Fizz    Karma   Camille       Lucian   
8        Sion      Nami     

## 2.3. EUW - Europe West

In [40]:
# Checking our shape
EUW.shape

(40000, 49)

In [41]:
# Checking our data types
EUW.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [42]:
# Checking for duplicated rows
EUW_Dups = EUW.duplicated()

In [43]:
# Flase records match count, indicating no dupplicates
EUW_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [44]:
EUW['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [45]:
EUW['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [46]:
EUW['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [47]:
EUW['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [48]:
EUW['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [49]:
# Checking values to see if anything is out of the ordinary
EUW.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0  40000.000000  40000.000000  40000.000000   
mean   3.743131e+09      11.0   1591.662600      0.500000      0.500000   
std    3.702796e+07       0.0    417.791747      0.500006      0.500006   
min    3.502776e+09      11.0    190.000000      0.000000      0.000000   
25%    3.731129e+09      11.0   1344.000000      0.000000      0.000000   
50%    3.750979e+09      11.0   1589.000000      0.500000      0.500000   
75%    3.769075e+09      11.0   1852.000000      1.000000      1.000000   
max    3.781290e+09      11.0   3828.000000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000    40000.000000  40000.000000   
mean      57.823775      0.498975      0.494600        0.438375      0.470775   
std       29.750664      0.500005      0.499977        0.496194      0.499151   
min        0.000000      0.000000      0.000000        0.000000      0.000000   
25%       39.000000      0.000000      0.000000        0.000000      0.000000   
50%       52.000000      0.000000      0.000000        0.000000      0.000000   
75%       70.000000      1.000000      1.000000        1.000000      1.000000   
max      458.000000      1.000000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.415350      0.338450     22.843525      5.383325   
std           0.492788      0.473188     10.509165      3.629596   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     15.000000      2.000000   
50%           0.000000      0.000000     22.000000      5.000000   
75%           1.000000      1.000000     30.000000      9.000000   
max           1.000000      1.000000     82.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.820825      1.162500         0.415350      0.419500   
std          1.056645      1.081676         0.492788      0.587689   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          0.000000      1.000000         0.000000      0.000000   
75%          1.000000      2.000000         1.000000      1.000000   
max         11.000000      6.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.591825      5.020525      5.083225      5.061075      5.086875   
std        3.718456      3.948030      4.004035      3.977875      4.046188   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      4.000000      4.000000      4.000000      4.000000   
75%        4.000000      7.000000      7.000000      7.000000      7.000000   
max       38.000000     29.000000     33.000000     30.000000     34.000000   

          soloKills      duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       4.817375      9.196700      7.088575      3.358750      0.881450  
std        3.296164      4.759567      4.129286      2.877813      1.389314  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        2.000000      6.000000      4.000000      1.000000      0.000000  
50%        4.000000      9.000000      7.000000      3.000000      0.000000  
75%        7.000000     12.000000     10.000000      5.000000      1.000000  
max       29.000000     40

In [50]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
EUW.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  3769279257        11          1703  <1537198685781    1     1           65   
1  3769279257        11          1703  <1537198685781    0     0           68   
2  3779209834        11          2022  <1537965779664    0     1           57   
3  3779209834        11          2022  <1537965779664    1     0           72   
4  3753102307        11          1436  <1535990846057    0     1           51   
5  3753102307        11          1436  <1535990846057    1     0           64   
6  3754388856        11          1134  <1536086013136    0     1           55   
7  3754388856        11          1134  <1536086013136    1     0           32   
8  3748860368        11          1277  <1535637677718    1     1           74   
9  3748860368        11          1277  <1535637677718    0     0           57   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           0               1            0                0   
1           1           1               0            1                1   
2           1           1               1            0                1   
3           0           0               0            1                0   
4           0           1               0            0                0   
5           1           0               1            1                1   
6           0           0               0            0                0   
7           1           1               1            1                1   
8           1           1               1            0                0   
9           0           0               0            1                1   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           1         18           7               2            0   
1           0         16           4               0            2   
2           1         24           9               1            2   
3           0         30           6               1            1   
4           0          5           2               0            1   
5           1         22          10               2            2   
6           0          4           1               0            0   
7           0         21           7               1            2   
8           0         28           7               1            1   
9           0         14           2               0            1   

   riftHeraldKills  baronKills     ban1      ban2      ban3      ban4  \
0                0           1    Akali   Leblanc    Irelia     Kaisa   
1                1           0    Akali    Darius    Aatrox      Olaf   
2                1           1    Akali    Draven    Darius   Alistar   
3                0           1  Nidalee  Kassadin    Aatrox    Irelia   
4                0           0   Draven   Evelynn     Yasuo    Khazix   
5                1           1  Leblanc    Aatrox    Draven     Akali   
6                0           0  Evelynn     Akali    Aatrox    No Ban   
7                1           0    Akali    Aatrox  Nocturne   Nidalee   
8                0           0   Aatrox    Twitch   Evelynn   Leblanc   
9                1           0   Twitch      Pyke   Evelynn  Kassadin   

       ban5        pick1      pick2     pick3        pick4        pick5  \
0    Draven        Urgot     Gragas     Rakan      Orianna        Sivir   
1    Irelia  AurelionSol     Graves    Syndra        Leona       Ezreal   
2   Camille     JarvanIV    Taliyah  Nautilus         Ryze        Kaisa   
3    Draven        Poppy       Pyke      Ekko      Karthus       Ezreal   
4     Akali         Nunu      Taric    Yorick  TwistedFate        Kaisa   
5  Kassadin      Kindred       Nami      Jhin      Chogath  Mordekaiser   
6      Ryze         Bard  Gangplank     Galio        Poppy     Tristana   
7   Camille        Kaisa   Nautilus   Leblanc         Kayn      Alistar   
8   Camille         Shen    Taliyah    Lucian    

In [51]:
# Creating our cleaned data frame
EUW_Clean = EUW.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [52]:
# Checking our shape for consistent row count and to ensure columns have been removed
EUW_Clean.shape

(40000, 39)

In [53]:
EUW_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  3769279257        11          1703  <1537198685781    1     1           65   
1  3769279257        11          1703  <1537198685781    0     0           68   
2  3779209834        11          2022  <1537965779664    0     1           57   
3  3779209834        11          2022  <1537965779664    1     0           72   
4  3753102307        11          1436  <1535990846057    0     1           51   
5  3753102307        11          1436  <1535990846057    1     0           64   
6  3754388856        11          1134  <1536086013136    0     1           55   
7  3754388856        11          1134  <1536086013136    1     0           32   
8  3748860368        11          1277  <1535637677718    1     1           74   
9  3748860368        11          1277  <1535637677718    0     0           57   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           0               1            0                0   
1           1           1               0            1                1   
2           1           1               1            0                1   
3           0           0               0            1                0   
4           0           1               0            0                0   
5           1           0               1            1                1   
6           0           0               0            0                0   
7           1           1               1            1                1   
8           1           1               1            0                0   
9           0           0               0            1                1   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           1         18           7               2            0   
1           0         16           4               0            2   
2           1         24           9               1            2   
3           0         30           6               1            1   
4           0          5           2               0            1   
5           1         22          10               2            2   
6           0          4           1               0            0   
7           0         21           7               1            2   
8           0         28           7               1            1   
9           0         14           2               0            1   

   riftHeraldKills  baronKills     ban1      ban2      ban3      ban4  \
0                0           1    Akali   Leblanc    Irelia     Kaisa   
1                1           0    Akali    Darius    Aatrox      Olaf   
2                1           1    Akali    Draven    Darius   Alistar   
3                0           1  Nidalee  Kassadin    Aatrox    Irelia   
4                0           0   Draven   Evelynn     Yasuo    Khazix   
5                1           1  Leblanc    Aatrox    Draven     Akali   
6                0           0  Evelynn     Akali    Aatrox    No Ban   
7                1           0    Akali    Aatrox  Nocturne   Nidalee   
8                0           0   Aatrox    Twitch   Evelynn   Leblanc   
9                1           0   Twitch      Pyke   Evelynn  Kassadin   

       ban5        pick1      pick2     pick3        pick4        pick5  \
0    Draven        Urgot     Gragas     Rakan      Orianna        Sivir   
1    Irelia  AurelionSol     Graves    Syndra        Leona       Ezreal   
2   Camille     JarvanIV    Taliyah  Nautilus         Ryze        Kaisa   
3    Draven        Poppy       Pyke      Ekko      Karthus       Ezreal   
4     Akali         Nunu      Taric    Yorick  TwistedFate        Kaisa   
5  Kassadin      Kindred       Nami      Jhin      Chogath  Mordekaiser   
6      Ryze         Bard  Gangplank     Galio        Poppy     Tristana   
7   Camille        Kaisa   Nautilus   Leblanc         Kayn      Alistar   
8   Camille         Shen    Taliyah    Lucian    

## 2.4. KR - Korea

In [54]:
# Checking our shape
KR.shape

(40000, 49)

In [55]:
# Checking our data types
KR.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [56]:
# Checking for duplicated rows
KR_Dups = KR.duplicated()

In [57]:
# Flase records match count, indicating no dupplicates
KR_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [58]:
KR['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [59]:
KR['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [60]:
KR['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [61]:
KR['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [62]:
KR['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [63]:
# Checking values to see if anything is out of the ordinary
KR.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0   40000.00000  40000.000000  40000.000000   
mean   3.323240e+09      11.0    1470.57765      0.500000      0.500000   
std    2.894908e+07       0.0     417.22998      0.500006      0.500006   
min    3.118168e+09      11.0     190.00000      0.000000      0.000000   
25%    3.309557e+09      11.0    1211.00000      0.000000      0.000000   
50%    3.326364e+09      11.0    1461.00000      0.500000      0.500000   
75%    3.346286e+09      11.0    1736.00000      1.000000      1.000000   
max    3.362165e+09      11.0    3424.00000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000    40000.000000  40000.000000   
mean      59.047125      0.498700      0.493225        0.367225      0.461600   
std       30.461361      0.500005      0.499960        0.482055      0.498529   
min        0.000000      0.000000      0.000000        0.000000      0.000000   
25%       38.000000      0.000000      0.000000        0.000000      0.000000   
50%       54.000000      0.000000      0.000000        0.000000      0.000000   
75%       73.000000      1.000000      1.000000        1.000000      1.000000   
max      305.000000      1.000000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.407925      0.293050     20.314100      4.590325   
std           0.491455      0.455167      9.882362      3.451411   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     13.000000      1.000000   
50%           0.000000      0.000000     20.000000      4.000000   
75%           1.000000      1.000000     27.000000      8.000000   
max           1.000000      1.000000     79.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.589350      1.011900         0.407925      0.353950   
std          0.867315      0.990875         0.491455      0.550751   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          0.000000      1.000000         0.000000      0.000000   
75%          1.000000      2.000000         1.000000      1.000000   
max          8.000000      6.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.301600      4.489975      4.517050      4.477000      4.528475   
std        3.388425      3.663514      3.671219      3.647849      3.673354   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      4.000000      4.000000      4.000000      4.000000   
75%        4.000000      6.000000      6.000000      6.000000      7.000000   
max       30.000000     30.000000     28.000000     28.000000     26.000000   

          soloKills     duoKills    trioKills     quadKills    pentaKills  
count  40000.000000  40000.00000  40000.00000  40000.000000  40000.000000  
mean       3.857000      7.98130      6.46155      3.280150      0.960300  
std        2.750325      4.33062      4.00154      2.952776      1.508768  
min        0.000000      0.00000      0.00000      0.000000      0.000000  
25%        2.000000      5.00000      3.00000      1.000000      0.000000  
50%        3.000000      8.00000      6.00000      3.000000      0.000000  
75%        5.000000     11.00000      9.00000      5.000000      1.000000  
max       23.000000     31.00000     25.00

In [64]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
KR.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  3295991456        11          1297  <1533397418579    0     1           72   
1  3295991456        11          1297  <1533397418579    1     0           50   
2  3332577742        11          1171  <1536135439439    1     1           35   
3  3332577742        11          1171  <1536135439439    0     0           44   
4  3309693654        11           943  <1534391613472    1     1           35   
5  3309693654        11           943  <1534391613472    0     0           28   
6  3342931485        11           965  <1536934006427    0     1           25   
7  3342931485        11           965  <1536934006427    1     0           47   
8  3330279592        11          1226  <1535951579933    0     1           37   
9  3330279592        11          1226  <1535951579933    1     0           52   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           1           0               0            0                0   
1           0           1               0            1                0   
2           1           0               1            1                1   
3           0           1               0            0                0   
4           1           1               0            1                0   
5           0           0               0            0                0   
6           0           0               0            0                0   
7           1           1               1            0                1   
8           0           1               0            0                0   
9           1           0               0            1                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0         12           1               0            0   
1           0         18           4               0            1   
2           0         22           9               1            2   
3           0         24           2               0            0   
4           0         21           4               0            1   
5           0          9           0               0            0   
6           0          6           0               0            0   
7           0         10           7               1            0   
8           0          6           1               0            0   
9           0         20           4               0            1   

   riftHeraldKills  baronKills     ban1     ban2       ban3         ban4  \
0                0           0    Rakan    Kaisa   Nocturne    TahmKench   
1                0           0   No Ban  Taliyah        Zoe      Orianna   
2                1           0    Rakan  Alistar      Akali    Gangplank   
3                0           0    Akali    Kaisa     No Ban  MissFortune   
4                0           0    Garen  Trundle    Evelynn        Talon   
5                0           0    Yasuo  Camille      Quinn       Aatrox   
6                0           0     Pyke  Taliyah      Jayce  TwistedFate   
7                1           0  Leblanc    Kaisa  Gangplank         Pyke   
8                0           0   No Ban   Irelia    Taliyah      Nidalee   
9                0           0     Ryze   LeeSin    Camille        Kaisa   

      ban5    pick1       pick2    pick3      pick4    pick5  player1Kills  \
0   No Ban    Shaco      Syndra     Shen     Ezreal    Akali             0   
1  Nidalee   Aatrox        Ryze  Morgana      Varus  Camille             2   
2  Taliyah   Lucian     Leblanc  Camille  TahmKench   Irelia             1   
3  Evelynn     Ryze       Braum    Varus       Ornn  Kindred            12   
4  Taliyah   Gragas       Jayce    Akali    Karthus    Kaisa             0   
5    Garen     Pyke     DrMundo    Varus    Leblanc  XinZhao             3   
6    Rakan  Alistar  Cassiopeia  Camille      Fiora    Xayah             0   
7   No Ban  Morgana         Zoe   Lucian   Renekton  Nidalee       

In [65]:
# Creating our cleaned data frame
KR_Clean = KR.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [66]:
# Checking our shape for consistent row count and to ensure columns have been removed
KR_Clean.shape

(40000, 39)

In [67]:
KR_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  3295991456        11          1297  <1533397418579    0     1           72   
1  3295991456        11          1297  <1533397418579    1     0           50   
2  3332577742        11          1171  <1536135439439    1     1           35   
3  3332577742        11          1171  <1536135439439    0     0           44   
4  3309693654        11           943  <1534391613472    1     1           35   
5  3309693654        11           943  <1534391613472    0     0           28   
6  3342931485        11           965  <1536934006427    0     1           25   
7  3342931485        11           965  <1536934006427    1     0           47   
8  3330279592        11          1226  <1535951579933    0     1           37   
9  3330279592        11          1226  <1535951579933    1     0           52   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           1           0               0            0                0   
1           0           1               0            1                0   
2           1           0               1            1                1   
3           0           1               0            0                0   
4           1           1               0            1                0   
5           0           0               0            0                0   
6           0           0               0            0                0   
7           1           1               1            0                1   
8           0           1               0            0                0   
9           1           0               0            1                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0         12           1               0            0   
1           0         18           4               0            1   
2           0         22           9               1            2   
3           0         24           2               0            0   
4           0         21           4               0            1   
5           0          9           0               0            0   
6           0          6           0               0            0   
7           0         10           7               1            0   
8           0          6           1               0            0   
9           0         20           4               0            1   

   riftHeraldKills  baronKills     ban1     ban2       ban3         ban4  \
0                0           0    Rakan    Kaisa   Nocturne    TahmKench   
1                0           0   No Ban  Taliyah        Zoe      Orianna   
2                1           0    Rakan  Alistar      Akali    Gangplank   
3                0           0    Akali    Kaisa     No Ban  MissFortune   
4                0           0    Garen  Trundle    Evelynn        Talon   
5                0           0    Yasuo  Camille      Quinn       Aatrox   
6                0           0     Pyke  Taliyah      Jayce  TwistedFate   
7                1           0  Leblanc    Kaisa  Gangplank         Pyke   
8                0           0   No Ban   Irelia    Taliyah      Nidalee   
9                0           0     Ryze   LeeSin    Camille        Kaisa   

      ban5    pick1       pick2    pick3      pick4    pick5  player1Kills  \
0   No Ban    Shaco      Syndra     Shen     Ezreal    Akali             0   
1  Nidalee   Aatrox        Ryze  Morgana      Varus  Camille             2   
2  Taliyah   Lucian     Leblanc  Camille  TahmKench   Irelia             1   
3  Evelynn     Ryze       Braum    Varus       Ornn  Kindred            12   
4  Taliyah   Gragas       Jayce    Akali    Karthus    Kaisa             0   
5    Garen     Pyke     DrMundo    Varus    Leblanc  XinZhao             3   
6    Rakan  Alistar  Cassiopeia  Camille      Fiora    Xayah             0   
7   No Ban  Morgana         Zoe   Lucian   Renekton  Nidalee       

## 2.5. LAN - Latin America North

In [68]:
# Checking our shape
LAN.shape

(40000, 49)

In [69]:
# Checking our data types
LAN.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [70]:
# Checking for duplicated rows
LAN_Dups = LAN.duplicated()

In [71]:
# Flase records match count, indicating no dupplicates
LAN_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [72]:
LAN['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [73]:
LAN['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [74]:
LAN['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [75]:
LAN['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [76]:
LAN['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [77]:
# Checking values to see if anything is out of the ordinary
LAN.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0  40000.000000  40000.000000  40000.000000   
mean   5.923949e+08      11.0   1653.403800      0.500000      0.500000   
std    1.782744e+07       0.0    487.317244      0.500006      0.500006   
min    5.156274e+08      11.0    190.000000      0.000000      0.000000   
25%    5.856455e+08      11.0   1409.000000      0.000000      0.000000   
50%    5.978678e+08      11.0   1669.000000      0.500000      0.500000   
75%    6.045803e+08      11.0   1946.000000      1.000000      1.000000   
max    6.116197e+08      11.0   4429.000000      1.000000      1.000000   

        wardsPlaced   firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.00000  40000.000000    40000.000000  40000.000000   
mean      57.425725      0.49600      0.480525        0.449150      0.474650   
std       32.611786      0.49999      0.499627        0.497414      0.499363   
min        0.000000      0.00000      0.000000        0.000000      0.000000   
25%       38.000000      0.00000      0.000000        0.000000      0.000000   
50%       51.000000      0.00000      0.000000        0.000000      0.000000   
75%       70.000000      1.00000      1.000000        1.000000      1.000000   
max      478.000000      1.00000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.396350      0.331050     23.217925      5.484600   
std           0.489145      0.470597     11.220382      3.871445   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     16.000000      2.000000   
50%           0.000000      0.000000     23.000000      6.000000   
75%           1.000000      1.000000     30.000000      9.000000   
max           1.000000      1.000000     82.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.945550      1.333725         0.396350      0.409150   
std          1.179394      1.169845         0.489145      0.583956   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          0.000000      1.000000         0.000000      0.000000   
75%          2.000000      2.000000         1.000000      1.000000   
max          8.000000      7.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.649200      5.154675      5.156500      5.130050      5.127500   
std        3.867727      4.136397      4.155044      4.155667      4.149099   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      4.000000      4.000000      4.000000      4.000000   
75%        4.000000      7.000000      7.000000      7.000000      7.000000   
max       36.000000     32.000000     37.000000     33.000000     30.000000   

          soloKills      duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       5.095950      9.193025      7.069225      3.492675      0.924825  
std        3.493122      5.012439      4.262521      3.012594      1.430952  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        3.000000      6.000000      4.000000      1.000000      0.000000  
50%        5.000000      9.000000      7.000000      3.000000      0.000000  
75%        7.000000     12.000000     10.000000      5.000000      1.000000  
max       32.000000     41.000000  

In [78]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
LAN.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  601946527        11          1777  <1536160575335    1     1           55   
1  601946527        11          1777  <1536160575335    0     0           66   
2  608493114        11          1383  <1537485500182    0     1           35   
3  608493114        11          1383  <1537485500182    1     0           35   
4  559800652        11          1842  <1526507802420    1     1           60   
5  559800652        11          1842  <1526507802420    0     0           96   
6  598630340        11          1246  <1535298348539    0     1           43   
7  598630340        11          1246  <1535298348539    1     0           80   
8  603180767        11          1270  <1536470778654    1     1           17   
9  603180767        11          1270  <1536470778654    0     0           29   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           1               1            0                1   
1           1           0               0            1                0   
2           0           0               0            0                0   
3           1           1               1            1                0   
4           0           1               1            1                1   
5           1           0               0            0                0   
6           0           0               0            0                1   
7           1           1               1            1                0   
8           0           1               0            0                0   
9           1           0               0            1                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           1         27          11               3            0   
1           0         16           1               0            2   
2           0         10           0               0            0   
3           0         21           8               1            1   
4           0         23           8               1            3   
5           1         21           4               0            0   
6           0          6           2               0            0   
7           0         17           8               1            1   
8           1         24           4               0            0   
9           0         24           1               0            1   

   riftHeraldKills  baronKills     ban1     ban2      ban3          ban4  \
0                1           1   Lucian    Akali    Irelia      Vladimir   
1                0           0  Evelynn      Jax    Draven         Yasuo   
2                0           0   Irelia      Zed     Diana    Tryndamere   
3                0           0   Thresh      Zoe    Graves     Gangplank   
4                1           0  Caitlyn  Leblanc     Rakan       Sejuani   
5                0           1  DrMundo   Anivia    Rengar      Vladimir   
6                1           0    Kaisa  Camille       Jax        Aatrox   
7                0           0      Jax    Akali   Trundle        No Ban   
8                0           1   Draven    Quinn     Akali  Fiddlesticks   
9                0           0    Varus  Camille  Renekton       Morgana   

       ban5     pick1     pick2    pick3       pick4        pick5  \
0     Kaisa   Leblanc     Riven  Caitlyn     Morgana       Gragas   
1     Akali    Zilean    Graves     Pyke        Jhin      Camille   
2  Vladimir     Kaisa     Poppy  Alistar    Kassadin         Olaf   
3     Akali       Zac       Jax  Karthus      Lucian         Lulu   
4    Irelia      Gnar  Kassadin   Graves  Blitzcrank         Jhin   
5       Zoe      Ahri    Ezreal     Kayn       Braum        Fiora   
6     Akali   DrMundo     Rakan     Jhin      Khazix     Vladimir   
7    Irelia      Pyke   Warwick   Draven       Yasuo  Mordekaiser   
8    No Ban  Vladimir    Graves    Kaisa        Pyke         Sion   
9     Rakan

In [79]:
# Creating our cleaned data frame
LAN_Clean = LAN.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [80]:
# Checking our shape for consistent row count and to ensure columns have been removed
LAN_Clean.shape

(40000, 39)

In [81]:
LAN_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  601946527        11          1777  <1536160575335    1     1           55   
1  601946527        11          1777  <1536160575335    0     0           66   
2  608493114        11          1383  <1537485500182    0     1           35   
3  608493114        11          1383  <1537485500182    1     0           35   
4  559800652        11          1842  <1526507802420    1     1           60   
5  559800652        11          1842  <1526507802420    0     0           96   
6  598630340        11          1246  <1535298348539    0     1           43   
7  598630340        11          1246  <1535298348539    1     0           80   
8  603180767        11          1270  <1536470778654    1     1           17   
9  603180767        11          1270  <1536470778654    0     0           29   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           1               1            0                1   
1           1           0               0            1                0   
2           0           0               0            0                0   
3           1           1               1            1                0   
4           0           1               1            1                1   
5           1           0               0            0                0   
6           0           0               0            0                1   
7           1           1               1            1                0   
8           0           1               0            0                0   
9           1           0               0            1                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           1         27          11               3            0   
1           0         16           1               0            2   
2           0         10           0               0            0   
3           0         21           8               1            1   
4           0         23           8               1            3   
5           1         21           4               0            0   
6           0          6           2               0            0   
7           0         17           8               1            1   
8           1         24           4               0            0   
9           0         24           1               0            1   

   riftHeraldKills  baronKills     ban1     ban2      ban3          ban4  \
0                1           1   Lucian    Akali    Irelia      Vladimir   
1                0           0  Evelynn      Jax    Draven         Yasuo   
2                0           0   Irelia      Zed     Diana    Tryndamere   
3                0           0   Thresh      Zoe    Graves     Gangplank   
4                1           0  Caitlyn  Leblanc     Rakan       Sejuani   
5                0           1  DrMundo   Anivia    Rengar      Vladimir   
6                1           0    Kaisa  Camille       Jax        Aatrox   
7                0           0      Jax    Akali   Trundle        No Ban   
8                0           1   Draven    Quinn     Akali  Fiddlesticks   
9                0           0    Varus  Camille  Renekton       Morgana   

       ban5     pick1     pick2    pick3       pick4        pick5  \
0     Kaisa   Leblanc     Riven  Caitlyn     Morgana       Gragas   
1     Akali    Zilean    Graves     Pyke        Jhin      Camille   
2  Vladimir     Kaisa     Poppy  Alistar    Kassadin         Olaf   
3     Akali       Zac       Jax  Karthus      Lucian         Lulu   
4    Irelia      Gnar  Kassadin   Graves  Blitzcrank         Jhin   
5       Zoe      Ahri    Ezreal     Kayn       Braum        Fiora   
6     Akali   DrMundo     Rakan     Jhin      Khazix     Vladimir   
7    Irelia      Pyke   Warwick   Draven       Yasuo  Mordekaiser   
8    No Ban  Vladimir    Graves    Kaisa        Pyke         Sion   
9     Rakan

## 2.6. LAS - Latin America South

In [82]:
# Checking our shape
LAS.shape

(40000, 49)

In [83]:
# Checking our data types
LAS.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [84]:
# Checking for duplicated rows
LAS_Dups = LAS.duplicated()

In [85]:
# Flase records match count, indicating no dupplicates
LAS_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [86]:
LAS['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [87]:
LAS['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [88]:
LAS['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [89]:
LAS['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [90]:
LAS['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [91]:
# Checking values to see if anything is out of the ordinary
LAS.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0  40000.000000  40000.000000  40000.000000   
mean   6.075362e+08      11.0   1652.859000      0.500000      0.500000   
std    1.369200e+07       0.0    467.336513      0.500006      0.500006   
min    5.401589e+08      11.0    190.000000      0.000000      0.000000   
25%    6.041053e+08      11.0   1408.000000      0.000000      0.000000   
50%    6.117076e+08      11.0   1665.000000      0.500000      0.500000   
75%    6.168074e+08      11.0   1939.000000      1.000000      1.000000   
max    6.208046e+08      11.0   3796.000000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000    40000.000000  40000.000000   
mean      59.047650      0.496325      0.484350        0.449075      0.475775   
std       31.550559      0.499993      0.499761        0.497406      0.499419   
min        0.000000      0.000000      0.000000        0.000000      0.000000   
25%       40.000000      0.000000      0.000000        0.000000      0.000000   
50%       54.000000      0.000000      0.000000        0.000000      0.000000   
75%       72.000000      1.000000      1.000000        1.000000      1.000000   
max      350.000000      1.000000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.409925      0.338650     22.821000      5.539575   
std           0.491826      0.473257     10.756765      3.812984   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     15.000000      2.000000   
50%           0.000000      0.000000     23.000000      6.000000   
75%           1.000000      1.000000     30.000000      9.000000   
max           1.000000      1.000000     73.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.931075      1.319275         0.409925      0.421000   
std          1.154278      1.158219         0.491826      0.588912   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          0.000000      1.000000         0.000000      0.000000   
75%          2.000000      2.000000         1.000000      1.000000   
max         11.000000      6.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.596100      5.014550      5.056675      5.078700      5.074975   
std        3.764687      3.952882      4.032471      4.011871      4.040503   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      4.000000      4.000000      4.000000      4.000000   
75%        4.000000      7.000000      7.000000      7.000000      7.000000   
max       31.000000     31.000000     30.000000     29.000000     33.000000   

          soloKills      duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       4.928650      9.079075      6.988675      3.434475      0.910450  
std        3.342961      4.829084      4.146224      2.921724      1.403453  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        2.000000      6.000000      4.000000      1.000000      0.000000  
50%        4.000000      9.000000      7.000000      3.000000      0.000000  
75%        7.000000     12.000000     10.000000      5.000000      1.000000  
max       31.000000     33

In [92]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
LAS.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  588448718        11          1616  <1529289528097    1     1           51   
1  588448718        11          1616  <1529289528097    0     0           46   
2  619545313        11          1410  <1537819106706    1     1           60   
3  619545313        11          1410  <1537819106706    0     0           49   
4  579478674        11          1854  <1526911011994    0     1           74   
5  579478674        11          1854  <1526911011994    1     0           70   
6  618280668        11          1750  <1537508159465    0     1           49   
7  618280668        11          1750  <1537508159465    1     0          119   
8  601110031        11          1321  <1532722906558    1     1           31   
9  601110031        11          1321  <1532722906558    0     0           47   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           1           1               1            1                1   
1           0           0               0            0                0   
2           0           1               1            1                1   
3           1           0               0            0                0   
4           0           1               0            1                0   
5           1           0               1            0                1   
6           0           0               0            0                0   
7           1           1               1            1                1   
8           0           1               1            1                1   
9           1           0               0            0                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           1         26           8               1            1   
1           0         30           1               0            1   
2           1         20           6               1            1   
3           0         17           4               0            1   
4           0         14           4               0            1   
5           1         22          11               3            2   
6           1         17           1               0            0   
7           0         39           9               1            3   
8           1         24           9               1            2   
9           0         21           0               0            0   

   riftHeraldKills  baronKills       ban1      ban2      ban3      ban4  \
0                1           1     Draven  MasterYi   Chogath       Zoe   
1                0           0      Yasuo   Morgana    Darius      Lulu   
2                1           1    Camille      Sion       Zed    Khazix   
3                0           0      Akali    Kennen    No Ban  Vladimir   
4                0           0    Camille  Vladimir    Darius     Shaco   
5                1           1      Shaco    No Ban    Singed    Khazix   
6                0           1     Khazix     Akali    Irelia     Kaisa   
7                1           0  Gangplank      Bard     Akali    Aatrox   
8                1           1   Vladimir    Graves     Talon       Jax   
9                0           0      Brand    Aatrox  Nocturne     Quinn   

         ban5     pick1         pick2     pick3        pick4         pick5  \
0      Zilean     Kaisa          Pyke  Renekton          Zed  Fiddlesticks   
1      Irelia       Zac        Lucian     Brand        Garen         Talon   
2      Irelia      Kayn        Thresh      Jinx  AurelionSol         Riven   
3     Camille     Braum        Lucian    Darius        Elise       Leblanc   
4       Yasuo      Sion         Xayah      Nunu          Zoe         Rakan   
5      Irelia     Fiora         Braum    Graves      Leblanc        Ezreal   
6  Cassiopeia  Malphite          Pyke   Leblanc        Swain        Graves   
7      No Ban     Yasuo        Lucian   Camille         Shen       Trundle   
8      No 

In [93]:
# Creating our cleaned data frame
LAS_Clean = LAS.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [94]:
# Checking our shape for consistent row count and to ensure columns have been removed
LAS_Clean.shape

(40000, 39)

In [95]:
LAS_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  588448718        11          1616  <1529289528097    1     1           51   
1  588448718        11          1616  <1529289528097    0     0           46   
2  619545313        11          1410  <1537819106706    1     1           60   
3  619545313        11          1410  <1537819106706    0     0           49   
4  579478674        11          1854  <1526911011994    0     1           74   
5  579478674        11          1854  <1526911011994    1     0           70   
6  618280668        11          1750  <1537508159465    0     1           49   
7  618280668        11          1750  <1537508159465    1     0          119   
8  601110031        11          1321  <1532722906558    1     1           31   
9  601110031        11          1321  <1532722906558    0     0           47   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           1           1               1            1                1   
1           0           0               0            0                0   
2           0           1               1            1                1   
3           1           0               0            0                0   
4           0           1               0            1                0   
5           1           0               1            0                1   
6           0           0               0            0                0   
7           1           1               1            1                1   
8           0           1               1            1                1   
9           1           0               0            0                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           1         26           8               1            1   
1           0         30           1               0            1   
2           1         20           6               1            1   
3           0         17           4               0            1   
4           0         14           4               0            1   
5           1         22          11               3            2   
6           1         17           1               0            0   
7           0         39           9               1            3   
8           1         24           9               1            2   
9           0         21           0               0            0   

   riftHeraldKills  baronKills       ban1      ban2      ban3      ban4  \
0                1           1     Draven  MasterYi   Chogath       Zoe   
1                0           0      Yasuo   Morgana    Darius      Lulu   
2                1           1    Camille      Sion       Zed    Khazix   
3                0           0      Akali    Kennen    No Ban  Vladimir   
4                0           0    Camille  Vladimir    Darius     Shaco   
5                1           1      Shaco    No Ban    Singed    Khazix   
6                0           1     Khazix     Akali    Irelia     Kaisa   
7                1           0  Gangplank      Bard     Akali    Aatrox   
8                1           1   Vladimir    Graves     Talon       Jax   
9                0           0      Brand    Aatrox  Nocturne     Quinn   

         ban5     pick1         pick2     pick3        pick4         pick5  \
0      Zilean     Kaisa          Pyke  Renekton          Zed  Fiddlesticks   
1      Irelia       Zac        Lucian     Brand        Garen         Talon   
2      Irelia      Kayn        Thresh      Jinx  AurelionSol         Riven   
3     Camille     Braum        Lucian    Darius        Elise       Leblanc   
4       Yasuo      Sion         Xayah      Nunu          Zoe         Rakan   
5      Irelia     Fiora         Braum    Graves      Leblanc        Ezreal   
6  Cassiopeia  Malphite          Pyke   Leblanc        Swain        Graves   
7      No Ban     Yasuo        Lucian   Camille         Shen       Trundle   
8      No 

## 2.7. NA - North America

In [96]:
# Checking our shape
NA.shape

(40000, 49)

In [97]:
# Checking our data types
NA.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [98]:
# Checking for duplicated rows
NA_Dups = NA.duplicated()

In [99]:
# Flase records match count, indicating no dupplicates
NA_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [100]:
NA['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [101]:
NA['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [102]:
NA['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [103]:
NA['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [104]:
NA['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [105]:
# Checking values to see if anything is out of the ordinary
NA.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0   40000.00000  40000.000000  40000.000000   
mean   2.850755e+09      11.0    1592.48060      0.500000      0.500000   
std    2.294253e+07       0.0     412.15794      0.500006      0.500006   
min    2.695271e+09      11.0     190.00000      0.000000      0.000000   
25%    2.839793e+09      11.0    1341.00000      0.000000      0.000000   
50%    2.856247e+09      11.0    1580.00000      0.500000      0.500000   
75%    2.868047e+09      11.0    1846.00000      1.000000      1.000000   
max    2.876101e+09      11.0    4268.00000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000    40000.000000  40000.000000   
mean      57.106575      0.499125      0.495075        0.433425      0.482000   
std       29.568040      0.500005      0.499982        0.495554      0.499682   
min        0.000000      0.000000      0.000000        0.000000      0.000000   
25%       38.000000      0.000000      0.000000        0.000000      0.000000   
50%       51.000000      0.000000      0.000000        0.000000      0.000000   
75%       69.000000      1.000000      1.000000        1.000000      1.000000   
max      439.000000      1.000000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.418575      0.341825     22.348500      5.247275   
std           0.493332      0.474327     10.208279      3.612244   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     15.000000      2.000000   
50%           0.000000      0.000000     22.000000      5.000000   
75%           1.000000      1.000000     29.000000      9.000000   
max           1.000000      1.000000     83.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.808100      1.251725         0.418575      0.422750   
std          1.051381      1.107470         0.493332      0.590204   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          0.000000      1.000000         0.000000      0.000000   
75%          1.000000      2.000000         1.000000      1.000000   
max          9.000000      6.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.545275      4.932150      4.964025      4.934025      4.973025   
std        3.665950      3.882393      3.903506      3.869541      3.876496   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      4.000000      4.000000      4.000000      4.000000   
75%        4.000000      7.000000      7.000000      7.000000      7.000000   
max       29.000000     29.000000     32.000000     30.000000     30.000000   

          soloKills      duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       4.388275      8.692800      7.074950      3.628775      1.021050  
std        3.001440      4.494979      4.066853      3.000990      1.477096  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        2.000000      5.000000      4.000000      1.000000      0.000000  
50%        4.000000      8.000000      7.000000      3.000000      0.000000  
75%        6.000000     11.000000     10.000000      5.000000      2.000000  
max       26.000000     33

In [106]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
NA.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  2851249532        11          1664  <1534956218774    0     1           42   
1  2851249532        11          1664  <1534956218774    1     0           85   
2  2834816766        11          1636  <1532821841131    0     1          114   
3  2834816766        11          1636  <1532821841131    1     0           43   
4  2847558201        11          1555  <1534440349116    1     1           39   
5  2847558201        11          1555  <1534440349116    0     0           72   
6  2863303007        11          1734  <1536659517581    1     1           76   
7  2863303007        11          1734  <1536659517581    0     0           74   
8  2849793504        11          1450  <1534730773413    0     1           33   
9  2849793504        11          1450  <1534730773413    1     0           54   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           1           1               0            1                1   
1           0           0               1            0                0   
2           0           0               0            0                0   
3           1           1               1            1                1   
4           1           0               1            0                1   
5           0           1               0            1                0   
6           1           1               1            1                1   
7           0           0               0            0                0   
8           0           0               0            0                0   
9           1           1               1            1                1   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0         13           3               0            1   
1           1         23          10               2            2   
2           0         10           0               0            0   
3           1         24           9               2            3   
4           1         29           9               2            1   
5           0         17           5               0            2   
6           0         27           7               2            2   
7           0         35           2               0            1   
8           0         15           0               0            1   
9           1         21          11               2            1   

   riftHeraldKills  baronKills     ban1      ban2       ban3     ban4  \
0                1           0  Evelynn     Akali      Talon  Hecarim   
1                0           1    Akali     Talon        Zoe   Irelia   
2                0           0    Jayce  Vladimir     Graves   Rengar   
3                1           1    Quinn      Pyke     Graves   Draven   
4                1           1   Graves   Kindred  TahmKench   Rengar   
5                0           0    Leona       Zed        Zoe   KogMaw   
6                1           0   Aatrox    Irelia      Riven  Evelynn   
7                0           0    Jayce     Akali     Syndra  Morgana   
8                0           0   Aatrox  Vladimir    Kindred    Akali   
9                1           1   Draven       Zoe    DrMundo    Akali   

           ban5       pick1     pick2        pick3     pick4     pick5  \
0       Camille      Soraka  Vladimir       Rengar  Malzahar   Nidalee   
1        Draven  Blitzcrank    Rumble        Kaisa      Ryze    Khazix   
2         Talon      Ezreal      Kayn  TwistedFate      Zyra  Renekton   
3       Camille     Orianna   Kindred      DrMundo      Lulu     Varus   
4  Fiddlesticks         Lux      Jhin       LeeSin       Jax   Alistar   
5          Pyke        Udyr   Trundle       Draven     Brand      Fizz   
6    Blitzcrank     Nidalee      Sion         Sona    Lucian    Velkoz   
7        Draven    Malzahar    Twitch      Camille    Gragas    Thresh   
8        Rengar      Graves     Xayah      Orianna     Gar

In [107]:
# Creating our cleaned data frame
NA_Clean = NA.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [108]:
# Checking our shape for consistent row count and to ensure columns have been removed
NA_Clean.shape

(40000, 39)

In [109]:
NA_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  2851249532        11          1664  <1534956218774    0     1           42   
1  2851249532        11          1664  <1534956218774    1     0           85   
2  2834816766        11          1636  <1532821841131    0     1          114   
3  2834816766        11          1636  <1532821841131    1     0           43   
4  2847558201        11          1555  <1534440349116    1     1           39   
5  2847558201        11          1555  <1534440349116    0     0           72   
6  2863303007        11          1734  <1536659517581    1     1           76   
7  2863303007        11          1734  <1536659517581    0     0           74   
8  2849793504        11          1450  <1534730773413    0     1           33   
9  2849793504        11          1450  <1534730773413    1     0           54   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           1           1               0            1                1   
1           0           0               1            0                0   
2           0           0               0            0                0   
3           1           1               1            1                1   
4           1           0               1            0                1   
5           0           1               0            1                0   
6           1           1               1            1                1   
7           0           0               0            0                0   
8           0           0               0            0                0   
9           1           1               1            1                1   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0         13           3               0            1   
1           1         23          10               2            2   
2           0         10           0               0            0   
3           1         24           9               2            3   
4           1         29           9               2            1   
5           0         17           5               0            2   
6           0         27           7               2            2   
7           0         35           2               0            1   
8           0         15           0               0            1   
9           1         21          11               2            1   

   riftHeraldKills  baronKills     ban1      ban2       ban3     ban4  \
0                1           0  Evelynn     Akali      Talon  Hecarim   
1                0           1    Akali     Talon        Zoe   Irelia   
2                0           0    Jayce  Vladimir     Graves   Rengar   
3                1           1    Quinn      Pyke     Graves   Draven   
4                1           1   Graves   Kindred  TahmKench   Rengar   
5                0           0    Leona       Zed        Zoe   KogMaw   
6                1           0   Aatrox    Irelia      Riven  Evelynn   
7                0           0    Jayce     Akali     Syndra  Morgana   
8                0           0   Aatrox  Vladimir    Kindred    Akali   
9                1           1   Draven       Zoe    DrMundo    Akali   

           ban5       pick1     pick2        pick3     pick4     pick5  \
0       Camille      Soraka  Vladimir       Rengar  Malzahar   Nidalee   
1        Draven  Blitzcrank    Rumble        Kaisa      Ryze    Khazix   
2         Talon      Ezreal      Kayn  TwistedFate      Zyra  Renekton   
3       Camille     Orianna   Kindred      DrMundo      Lulu     Varus   
4  Fiddlesticks         Lux      Jhin       LeeSin       Jax   Alistar   
5          Pyke        Udyr   Trundle       Draven     Brand      Fizz   
6    Blitzcrank     Nidalee      Sion         Sona    Lucian    Velkoz   
7        Draven    Malzahar    Twitch      Camille    Gragas    Thresh   
8        Rengar      Graves     Xayah      Orianna     Gar

## 2.8. OC - Oceania

In [110]:
# Checking our shape
OC.shape

(40000, 49)

In [111]:
# Checking our data types
OC.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [112]:
# Checking for duplicated rows
OC_Dups = OC.duplicated()

In [113]:
# Flase records match count, indicating no dupplicates
OC_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [114]:
OC['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [115]:
OC['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [116]:
OC['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [117]:
OC['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [118]:
OC['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [119]:
# Checking values to see if anything is out of the ordinary
OC.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0  40000.000000  40000.000000  40000.000000   
mean   2.142397e+08      11.0   1687.589200      0.500000      0.500000   
std    5.245836e+06       0.0    439.208263      0.500006      0.500006   
min    1.976884e+08      11.0    190.000000      0.000000      0.000000   
25%    2.117237e+08      11.0   1423.000000      0.000000      0.000000   
50%    2.162465e+08      11.0   1679.000000      0.500000      0.500000   
75%    2.181165e+08      11.0   1958.000000      1.000000      1.000000   
max    2.199544e+08      11.0   3723.000000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000    40000.000000  40000.000000   
mean      56.606425      0.498650      0.491475        0.447300      0.483500   
std       30.557681      0.500004      0.499934        0.497221      0.499734   
min        0.000000      0.000000      0.000000        0.000000      0.000000   
25%       37.000000      0.000000      0.000000        0.000000      0.000000   
50%       50.000000      0.000000      0.000000        0.000000      0.000000   
75%       68.000000      1.000000      1.000000        1.000000      1.000000   
max      477.000000      1.000000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.357875      0.339500     24.800425      5.514400   
std           0.479381      0.473546     11.175069      3.790053   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     17.000000      2.000000   
50%           0.000000      0.000000     24.000000      6.000000   
75%           1.000000      1.000000     32.000000      9.000000   
max           1.000000      1.000000     80.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.934900      1.327150         0.357875      0.424600   
std          1.172602      1.158213         0.479381      0.595041   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          0.000000      1.000000         0.000000      0.000000   
75%          2.000000      2.000000         1.000000      1.000000   
max          9.000000      6.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.802900      5.478125      5.485250      5.509400      5.524750   
std        3.996943      4.263458      4.272796      4.265679      4.319468   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      5.000000      5.000000      5.000000      5.000000   
75%        5.000000      8.000000      8.000000      8.000000      8.000000   
max       32.000000     36.000000     34.000000     35.000000     31.000000   

         soloKills      duoKills     trioKills     quadKills    pentaKills  
count  40000.00000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       5.70350      9.972200      7.335900      3.537100      0.934750  
std        3.67668      5.103139      4.226691      2.988134      1.439772  
min        0.00000      0.000000      0.000000      0.000000      0.000000  
25%        3.00000      6.000000      4.000000      1.000000      0.000000  
50%        5.00000     10.000000      7.000000      3.000000      0.000000  
75%        8.00000     13.000000     10.000000      5.000000      1.000000  
max       33.00000     34.000000  

In [120]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
OC.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  217483703        11          1535  <1535795606150    0     1           43   
1  217483703        11          1535  <1535795606150    1     0           53   
2  208128437        11          2185  <1526402817218    1     1           63   
3  208128437        11          2185  <1526402817218    0     0           64   
4  206006696        11          1319  <1524068546792    0     1           24   
5  206006696        11          1319  <1524068546792    1     0           43   
6  213146439        11          1817  <1531139146291    0     1           43   
7  213146439        11          1817  <1531139146291    1     0           76   
8  218891904        11          1616  <1537138876286    1     1           34   
9  218891904        11          1616  <1537138876286    0     0           48   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           1           1               0            0                1   
1           0           0               1            1                0   
2           1           1               1            1                0   
3           0           0               0            0                1   
4           1           0               0            0                1   
5           0           1               1            1                0   
6           1           1               1            1                1   
7           0           0               0            0                0   
8           0           0               1            1                1   
9           1           1               0            0                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0          9           4               0            0   
1           1         32           9               2            2   
2           0         36          10               3            4   
3           1         55           6               0            0   
4           0          9           2               0            0   
5           1         25          10               2            2   
6           0         25           8               1            1   
7           1         30           9               1            2   
8           1         27           8               1            1   
9           0         23           4               0            0   

   riftHeraldKills  baronKills      ban1     ban2      ban3      ban4  \
0                1           0    Aatrox   Irelia   Leblanc   Evelynn   
1                0           1   Morgana   Anivia     Talon  Vladimir   
2                0           0      Kayn  Evelynn   Morgana    Graves   
3                1           2     Kaisa   Thresh   Morgana       Zed   
4                1           0     Fiora   Khazix  MasterYi      Ekko   
5                0           1    Illaoi   Khazix  Katarina    Thresh   
6                1           0   Evelynn  Leblanc  MasterYi    Darius   
7                0           1    Irelia    Xayah  Nocturne    Draven   
8                1           1      Nunu  Morgana     Brand     Fiora   
9                0           0  MasterYi     Ahri  Vladimir    Khazix   

           ban5       pick1        pick2    pick3      pick4    pick5  \
0         Akali       Fiora       Khazix  Alistar      Karma    Kaisa   
1          Fizz    Kassadin     JarvanIV    Rakan      Vayne     Udyr   
2          Fizz  Blitzcrank        Talon  Trundle  TahmKench   Ezreal   
3        Darius         Zac        Rakan    Brand      Teemo    Yasuo   
4       Caitlyn        Nunu         Lulu  Camille     Xerath     Jinx   
5           Zed         Lux       RekSai   Yorick      Vayne  Alistar   
6  Fiddlesticks        Olaf  MissFortune   LeeSin   Vladimir  XinZhao   
7           Zed        Jhin      Orianna   Aatrox       Lulu    Shaco   
8         Swain         Zac         Kled    Varus      Leona   Veigar   
9   

In [121]:
# Creating our cleaned data frame
OC_Clean = OC.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [122]:
# Checking our shape for consistent row count and to ensure columns have been removed
OC_Clean.shape

(40000, 39)

In [123]:
OC_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  217483703        11          1535  <1535795606150    0     1           43   
1  217483703        11          1535  <1535795606150    1     0           53   
2  208128437        11          2185  <1526402817218    1     1           63   
3  208128437        11          2185  <1526402817218    0     0           64   
4  206006696        11          1319  <1524068546792    0     1           24   
5  206006696        11          1319  <1524068546792    1     0           43   
6  213146439        11          1817  <1531139146291    0     1           43   
7  213146439        11          1817  <1531139146291    1     0           76   
8  218891904        11          1616  <1537138876286    1     1           34   
9  218891904        11          1616  <1537138876286    0     0           48   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           1           1               0            0                1   
1           0           0               1            1                0   
2           1           1               1            1                0   
3           0           0               0            0                1   
4           1           0               0            0                1   
5           0           1               1            1                0   
6           1           1               1            1                1   
7           0           0               0            0                0   
8           0           0               1            1                1   
9           1           1               0            0                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0          9           4               0            0   
1           1         32           9               2            2   
2           0         36          10               3            4   
3           1         55           6               0            0   
4           0          9           2               0            0   
5           1         25          10               2            2   
6           0         25           8               1            1   
7           1         30           9               1            2   
8           1         27           8               1            1   
9           0         23           4               0            0   

   riftHeraldKills  baronKills      ban1     ban2      ban3      ban4  \
0                1           0    Aatrox   Irelia   Leblanc   Evelynn   
1                0           1   Morgana   Anivia     Talon  Vladimir   
2                0           0      Kayn  Evelynn   Morgana    Graves   
3                1           2     Kaisa   Thresh   Morgana       Zed   
4                1           0     Fiora   Khazix  MasterYi      Ekko   
5                0           1    Illaoi   Khazix  Katarina    Thresh   
6                1           0   Evelynn  Leblanc  MasterYi    Darius   
7                0           1    Irelia    Xayah  Nocturne    Draven   
8                1           1      Nunu  Morgana     Brand     Fiora   
9                0           0  MasterYi     Ahri  Vladimir    Khazix   

           ban5       pick1        pick2    pick3      pick4    pick5  \
0         Akali       Fiora       Khazix  Alistar      Karma    Kaisa   
1          Fizz    Kassadin     JarvanIV    Rakan      Vayne     Udyr   
2          Fizz  Blitzcrank        Talon  Trundle  TahmKench   Ezreal   
3        Darius         Zac        Rakan    Brand      Teemo    Yasuo   
4       Caitlyn        Nunu         Lulu  Camille     Xerath     Jinx   
5           Zed         Lux       RekSai   Yorick      Vayne  Alistar   
6  Fiddlesticks        Olaf  MissFortune   LeeSin   Vladimir  XinZhao   
7           Zed        Jhin      Orianna   Aatrox       Lulu    Shaco   
8         Swain         Zac         Kled    Varus      Leona   Veigar   
9   

## 2.9. RU - Russia

In [124]:
# Checking our shape
RU.shape

(40000, 49)

In [125]:
# Checking our data types
RU.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [126]:
# Checking for duplicated rows
RU_Dups = RU.duplicated()

In [127]:
# Flase records match count, indicating no dupplicates
RU_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [128]:
RU['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [129]:
RU['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [130]:
RU['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [131]:
RU['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [132]:
RU['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [133]:
# Checking values to see if anything is out of the ordinary
RU.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0  40000.000000  40000.000000  40000.000000   
mean   1.822539e+08      11.0   1621.530850      0.500000      0.500000   
std    4.466955e+06       0.0    446.291516      0.500006      0.500006   
min    1.605087e+08      11.0    191.000000      0.000000      0.000000   
25%    1.807129e+08      11.0   1372.000000      0.000000      0.000000   
50%    1.835412e+08      11.0   1625.000000      0.500000      0.500000   
75%    1.853105e+08      11.0   1890.000000      1.000000      1.000000   
max    1.870359e+08      11.0   3561.000000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000    40000.000000  40000.000000   
mean      54.180000      0.497275      0.487200        0.450675      0.477175   
std       32.039049      0.499999      0.499842        0.497567      0.499485   
min        0.000000      0.000000      0.000000        0.000000      0.000000   
25%       35.000000      0.000000      0.000000        0.000000      0.000000   
50%       47.000000      0.000000      0.000000        0.000000      0.000000   
75%       65.000000      1.000000      1.000000        1.000000      1.000000   
max      434.000000      1.000000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.358800      0.323325     25.429075      5.425725   
std           0.479654      0.467751     11.821441      3.777121   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     17.000000      2.000000   
50%           0.000000      0.000000     25.000000      6.000000   
75%           1.000000      1.000000     33.000000      9.000000   
max           1.000000      1.000000     86.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills   baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.00000   
mean         0.892375      1.259300         0.358800      0.39715   
std          1.113967      1.132672         0.479654      0.57596   
min          0.000000      0.000000         0.000000      0.00000   
25%          0.000000      0.000000         0.000000      0.00000   
50%          0.000000      1.000000         0.000000      0.00000   
75%          2.000000      2.000000         1.000000      1.00000   
max         10.000000      6.000000         1.000000      4.00000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.870025      5.605550      5.674250      5.604975      5.674275   
std        4.139935      4.386313      4.481126      4.413328      4.466377   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      5.000000      5.000000      5.000000      5.000000   
75%        5.000000      8.000000      8.000000      8.000000      8.000000   
max       34.000000     37.000000     35.000000     35.000000     38.000000   

          soloKills      duoKills     trioKills     quadKills   pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.00000  
mean       6.275600     10.588725      7.310075      3.268775      0.78770  
std        3.928623      5.443048      4.357884      2.913125      1.29326  
min        0.000000      0.000000      0.000000      0.000000      0.00000  
25%        3.000000      7.000000      4.000000      1.000000      0.00000  
50%        6.000000     10.000000      7.000000      3.000000      0.00000  
75%        9.000000     14.000000     10.000000      5.000000      1.00000  
max       29.000000     39.000000     29.00

In [134]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
RU.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  179026085        11          1613  <1531394680109    0     1           36   
1  179026085        11          1613  <1531394680109    1     0           44   
2  172500690        11          1411  <1526135446286    0     1           39   
3  172500690        11          1411  <1526135446286    1     0           45   
4  186295247        11          2296  <1537515741269    1     1           44   
5  186295247        11          2296  <1537515741269    0     0          152   
6  173212082        11           960  <1526820839230    0     1           57   
7  173212082        11           960  <1526820839230    1     0           32   
8  183530122        11          1536  <1535199810022    1     1           28   
9  183530122        11          1536  <1535199810022    0     0           54   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           0               0            0                0   
1           1           1               1            1                1   
2           1           1               0            0                0   
3           0           0               1            1                0   
4           1           0               0            1                0   
5           0           1               1            0                1   
6           0           0               0            1                0   
7           1           1               0            0                0   
8           1           1               1            0                1   
9           0           0               0            1                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0         11           0               0            0   
1           1         31          10               2            3   
2           0         20           4               0            0   
3           1         20           8               1            2   
4           0         58          11               3            2   
5           1         40           6               1            2   
6           0          6           0               0            1   
7           0         10           2               0            0   
8           1         28           8               1            2   
9           0         26           2               0            1   

   riftHeraldKills  baronKills      ban1      ban2     ban3        ban4  \
0                0           0     Kaisa       Zoe      Jax      No Ban   
1                1           1     Xayah   Morgana  Evelynn     Camille   
2                0           0     Kaisa  MasterYi  Leblanc      Graves   
3                0           1   Leblanc    No Ban   Graves  Tryndamere   
4                0           0  Renekton  Nocturne     Fizz         Zed   
5                1           2    Darius     Yasuo     Fizz         Zed   
6                0           0      Lulu  Pantheon   Graves      Darius   
7                0           0   Alistar     Akali     Kayn       Yasuo   
8                1           1  Malzahar   Evelynn     Kled       Akali   
9                0           0  Katarina   Evelynn   Velkoz    Nocturne   

       ban5    pick1     pick2     pick3     pick4   pick5  player1Kills  \
0  MasterYi    Garen  Malzahar      Udyr     Janna  Ezreal             1   
1       Zoe    Leona    Lucian       Zed    Aatrox  Wukong             2   
2      Sion    Vayne    Soraka  Katarina    Khazix   Yasuo             0   
3   Caitlyn  Morgana     Swain     Shaco    Wukong  Ezreal             2   
4     Yasuo   Irelia     Kaisa    Zilean    Khazix   Karma             0   
5  Malzahar    Teemo       Jax     Akali      Zyra    Jhin             2   
6     Kaisa    Talon     Leona   Warwick   Caitlyn   Riven             0   
7    No Ban  Morgana      Jhin   Leblanc  Nocturne     Zed             2   
8    Draven      Zed      Ud

In [135]:
# Creating our cleaned data frame
RU_Clean = RU.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [136]:
# Checking our shape for consistent row count and to ensure columns have been removed
RU_Clean.shape

(40000, 39)

In [137]:
RU_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  179026085        11          1613  <1531394680109    0     1           36   
1  179026085        11          1613  <1531394680109    1     0           44   
2  172500690        11          1411  <1526135446286    0     1           39   
3  172500690        11          1411  <1526135446286    1     0           45   
4  186295247        11          2296  <1537515741269    1     1           44   
5  186295247        11          2296  <1537515741269    0     0          152   
6  173212082        11           960  <1526820839230    0     1           57   
7  173212082        11           960  <1526820839230    1     0           32   
8  183530122        11          1536  <1535199810022    1     1           28   
9  183530122        11          1536  <1535199810022    0     0           54   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           0               0            0                0   
1           1           1               1            1                1   
2           1           1               0            0                0   
3           0           0               1            1                0   
4           1           0               0            1                0   
5           0           1               1            0                1   
6           0           0               0            1                0   
7           1           1               0            0                0   
8           1           1               1            0                1   
9           0           0               0            1                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           0         11           0               0            0   
1           1         31          10               2            3   
2           0         20           4               0            0   
3           1         20           8               1            2   
4           0         58          11               3            2   
5           1         40           6               1            2   
6           0          6           0               0            1   
7           0         10           2               0            0   
8           1         28           8               1            2   
9           0         26           2               0            1   

   riftHeraldKills  baronKills      ban1      ban2     ban3        ban4  \
0                0           0     Kaisa       Zoe      Jax      No Ban   
1                1           1     Xayah   Morgana  Evelynn     Camille   
2                0           0     Kaisa  MasterYi  Leblanc      Graves   
3                0           1   Leblanc    No Ban   Graves  Tryndamere   
4                0           0  Renekton  Nocturne     Fizz         Zed   
5                1           2    Darius     Yasuo     Fizz         Zed   
6                0           0      Lulu  Pantheon   Graves      Darius   
7                0           0   Alistar     Akali     Kayn       Yasuo   
8                1           1  Malzahar   Evelynn     Kled       Akali   
9                0           0  Katarina   Evelynn   Velkoz    Nocturne   

       ban5    pick1     pick2     pick3     pick4   pick5  player1Kills  \
0  MasterYi    Garen  Malzahar      Udyr     Janna  Ezreal             1   
1       Zoe    Leona    Lucian       Zed    Aatrox  Wukong             2   
2      Sion    Vayne    Soraka  Katarina    Khazix   Yasuo             0   
3   Caitlyn  Morgana     Swain     Shaco    Wukong  Ezreal             2   
4     Yasuo   Irelia     Kaisa    Zilean    Khazix   Karma             0   
5  Malzahar    Teemo       Jax     Akali      Zyra    Jhin             2   
6     Kaisa    Talon     Leona   Warwick   Caitlyn   Riven             0   
7    No Ban  Morgana      Jhin   Leblanc  Nocturne     Zed             2   
8    Draven      Zed      Ud

## 2.10. TR - Turkey

In [138]:
# Checking our shape
TR.shape

(40000, 49)

In [139]:
# Checking our data types
TR.dtypes

matchId             int64
seasonId            int64
gameDuration        int64
gameCreation       object
win                 int64
team                int64
wardsPlaced         int64
firstBlood          int64
firstTower          int64
firstInhibitor      int64
firstDragon         int64
firstRiftHerald     int64
firstBaron          int64
teamKills           int64
towerKills          int64
inhibitorKills      int64
dragonKills         int64
riftHeraldKills     int64
baronKills          int64
ban1               object
ban2               object
ban3               object
ban4               object
ban5               object
pick1              object
pick2              object
pick3              object
pick4              object
pick5              object
player1Kills        int64
player2Kills        int64
player3Kills        int64
player4Kills        int64
player5Kills        int64
spell1Player1      object
spell1Player2      object
spell1Player3      object
spell1Player4      object
spell1Player

In [140]:
# Checking for duplicated rows
TR_Dups = TR.duplicated()

In [141]:
# Flase records match count, indicating no dupplicates
TR_Dups.describe()

count     40000
unique        1
top       False
freq      40000
dtype: object

#### Replacing blank values that we described during our cleaning of BR Match Data

In [142]:
TR['ban1'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [143]:
TR['ban2'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [144]:
TR['ban3'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [145]:
TR['ban4'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [146]:
TR['ban5'].replace(r'^\s*$','No Ban',regex = True,inplace = True)

In [147]:
# Checking values to see if anything is out of the ordinary
TR.describe()

matchId  seasonId  gameDuration           win          team  \
count  4.000000e+04   40000.0  40000.000000  40000.000000  40000.000000   
mean   7.461931e+08      11.0   1616.671650      0.500000      0.500000   
std    1.465781e+07       0.0    421.113684      0.500006      0.500006   
min    6.578956e+08      11.0    190.000000      0.000000      0.000000   
25%    7.410105e+08      11.0   1380.000000      0.000000      0.000000   
50%    7.508297e+08      11.0   1621.500000      0.500000      0.500000   
75%    7.567323e+08      11.0   1879.000000      1.000000      1.000000   
max    7.609422e+08      11.0   3373.000000      1.000000      1.000000   

        wardsPlaced    firstBlood    firstTower  firstInhibitor   firstDragon  \
count  40000.000000  40000.000000  40000.000000    40000.000000  40000.000000   
mean      51.040600      0.498175      0.490100        0.457225      0.475325   
std       27.178511      0.500003      0.499908        0.498173      0.499397   
min        0.000000      0.000000      0.000000        0.000000      0.000000   
25%       34.000000      0.000000      0.000000        0.000000      0.000000   
50%       46.000000      0.000000      0.000000        0.000000      0.000000   
75%       62.000000      1.000000      1.000000        1.000000      1.000000   
max      418.000000      1.000000      1.000000        1.000000      1.000000   

       firstRiftHerald    firstBaron     teamKills    towerKills  \
count     40000.000000  40000.000000  40000.000000  40000.000000   
mean          0.371350      0.337500     25.292725      5.400350   
std           0.483172      0.472863     11.317881      3.740618   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000     17.000000      2.000000   
50%           0.000000      0.000000     25.000000      6.000000   
75%           1.000000      1.000000     33.000000      9.000000   
max           1.000000      1.000000     85.000000     11.000000   

       inhibitorKills   dragonKills  riftHeraldKills    baronKills  \
count    40000.000000  40000.000000     40000.000000  40000.000000   
mean         0.876300      1.209850         0.371350      0.417750   
std          1.084563      1.102245         0.483172      0.587744   
min          0.000000      0.000000         0.000000      0.000000   
25%          0.000000      0.000000         0.000000      0.000000   
50%          1.000000      1.000000         0.000000      0.000000   
75%          2.000000      2.000000         1.000000      1.000000   
max         10.000000      6.000000         1.000000      4.000000   

       player1Kills  player2Kills  player3Kills  player4Kills  player5Kills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       2.859050      5.561400      5.617650      5.637400      5.617225   
std        4.079203      4.268341      4.310548      4.359013      4.344304   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      2.000000      2.000000      2.000000      2.000000   
50%        1.000000      5.000000      5.000000      5.000000      5.000000   
75%        5.000000      8.000000      8.000000      8.000000      8.000000   
max       31.000000     33.000000     35.000000     33.000000     32.000000   

          soloKills      duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       5.960225     10.395225      7.471250      3.414350      0.853375  
std        3.753278      5.203489      4.273989      2.901866      1.346726  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        3.000000      7.000000      4.000000      1.000000      0.000000  
50%        5.000000     10.000000      7.000000      3.000000      0.000000  
75%        8.000000     14.000000     10.000000      5.000000      1.000000  
max       40.000000     40

In [148]:
# Checking data information for 5 matches, each match consists of 2 rows that share Unique matchid
TR.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  731078570        11          1857  <1531596997270    1     1           52   
1  731078570        11          1857  <1531596997270    0     0           50   
2  714068232        11          1259  <1528313184636    0     1           46   
3  714068232        11          1259  <1528313184636    1     0           64   
4  753628501        11          1246  <1536605813248    1     1           77   
5  753628501        11          1246  <1536605813248    0     0           42   
6  740446483        11          1621  <1533645559029    0     1           51   
7  740446483        11          1621  <1533645559029    1     0           48   
8  744172467        11          1620  <1534498099353    0     1           43   
9  744172467        11          1620  <1534498099353    1     0           67   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           1               1            0                1   
1           1           0               0            1                0   
2           0           0               0            0                0   
3           1           1               1            1                1   
4           1           1               1            1                1   
5           0           0               0            0                0   
6           0           1               0            1                0   
7           1           0               1            0                1   
8           0           1               0            1                1   
9           1           0               1            0                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           1         31          11               5            1   
1           0         27           0               0            1   
2           0         19           0               0            0   
3           0         28           8               1            2   
4           0         32           8               1            1   
5           0         26           2               0            0   
6           0         15           4               0            1   
7           1         35           8               1            2   
8           0         20           6               0            2   
9           1         34          11               3            1   

   riftHeraldKills  baronKills      ban1         ban2      ban3     ban4  \
0                1           2    Irelia      Camille     Braum   Thresh   
1                0           0   Camille        Yasuo  Vladimir     Pyke   
2                0           0    Irelia       Ezreal    Graves    Kaisa   
3                1           0  Renekton  TwistedFate     Rakan    Kaisa   
4                1           0    Graves        Akali    Gragas  Evelynn   
5                0           0   Morgana      Evelynn    Rengar  Alistar   
6                0           0     Talon      Kindred      Pyke    Shaco   
7                1           1     Akali      Kindred   Camille  Evelynn   
8                1           0       Zed      Camille     Akali   Draven   
9                0           1    No Ban        Xayah    Rengar    Rakan   

      ban5         pick1    pick2         pick3     pick4     pick5  \
0  Morgana  Fiddlesticks   Draven  Heimerdinger     Quinn   Evelynn   
1    Kaisa        Graves   Velkoz         Urgot    Soraka    Rengar   
2   Rengar       Camille     Fizz          Kayn      Ashe      Bard   
3  Leblanc        Lucian   Draven          Nami     Akali   Trundle   
4   Irelia          Zyra    Yasuo        Khazix     Fiora     Kaisa   
5   Zilean          Jhin     Nami          Gnar  JarvanIV     Galio   
6  Camille       Morgana   Gragas        Aatrox      Jhin    Kennen   
7    Rakan        LeeSin   Lucian         Braum    Velkoz  Vladimir   
8   Lucian         Janna  Kindred        Velkoz      Udyr     

In [149]:
# Creating our cleaned data frame
TR_Clean = TR.drop(columns = ['spell1Player1','spell1Player2','spell1Player3','spell1Player4','spell1Player5','spell2Player1','spell2Player2','spell2Player3','spell2Player4','spell2Player5'])

In [150]:
# Checking our shape for consistent row count and to ensure columns have been removed
TR_Clean.shape

(40000, 39)

In [151]:
TR_Clean.head(10)

matchId  seasonId  gameDuration    gameCreation  win  team  wardsPlaced  \
0  731078570        11          1857  <1531596997270    1     1           52   
1  731078570        11          1857  <1531596997270    0     0           50   
2  714068232        11          1259  <1528313184636    0     1           46   
3  714068232        11          1259  <1528313184636    1     0           64   
4  753628501        11          1246  <1536605813248    1     1           77   
5  753628501        11          1246  <1536605813248    0     0           42   
6  740446483        11          1621  <1533645559029    0     1           51   
7  740446483        11          1621  <1533645559029    1     0           48   
8  744172467        11          1620  <1534498099353    0     1           43   
9  744172467        11          1620  <1534498099353    1     0           67   

   firstBlood  firstTower  firstInhibitor  firstDragon  firstRiftHerald  \
0           0           1               1            0                1   
1           1           0               0            1                0   
2           0           0               0            0                0   
3           1           1               1            1                1   
4           1           1               1            1                1   
5           0           0               0            0                0   
6           0           1               0            1                0   
7           1           0               1            0                1   
8           0           1               0            1                1   
9           1           0               1            0                0   

   firstBaron  teamKills  towerKills  inhibitorKills  dragonKills  \
0           1         31          11               5            1   
1           0         27           0               0            1   
2           0         19           0               0            0   
3           0         28           8               1            2   
4           0         32           8               1            1   
5           0         26           2               0            0   
6           0         15           4               0            1   
7           1         35           8               1            2   
8           0         20           6               0            2   
9           1         34          11               3            1   

   riftHeraldKills  baronKills      ban1         ban2      ban3     ban4  \
0                1           2    Irelia      Camille     Braum   Thresh   
1                0           0   Camille        Yasuo  Vladimir     Pyke   
2                0           0    Irelia       Ezreal    Graves    Kaisa   
3                1           0  Renekton  TwistedFate     Rakan    Kaisa   
4                1           0    Graves        Akali    Gragas  Evelynn   
5                0           0   Morgana      Evelynn    Rengar  Alistar   
6                0           0     Talon      Kindred      Pyke    Shaco   
7                1           1     Akali      Kindred   Camille  Evelynn   
8                1           0       Zed      Camille     Akali   Draven   
9                0           1    No Ban        Xayah    Rengar    Rakan   

      ban5         pick1    pick2         pick3     pick4     pick5  \
0  Morgana  Fiddlesticks   Draven  Heimerdinger     Quinn   Evelynn   
1    Kaisa        Graves   Velkoz         Urgot    Soraka    Rengar   
2   Rengar       Camille     Fizz          Kayn      Ashe      Bard   
3  Leblanc        Lucian   Draven          Nami     Akali   Trundle   
4   Irelia          Zyra    Yasuo        Khazix     Fiora     Kaisa   
5   Zilean          Jhin     Nami          Gnar  JarvanIV     Galio   
6  Camille       Morgana   Gragas        Aatrox      Jhin    Kennen   
7    Rakan        LeeSin   Lucian         Braum    Velkoz  Vladimir   
8   Lucian         Janna  Kindred        Velkoz      Udyr     

# 3. Statistical Analysis

## 3.1 BR Match Data Analysis

In [152]:
# Quick data frame with only select columns for statistical analysis
BR_Stat = BR_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [153]:
BR_Stat.shape

(40000, 18)

In [154]:
BR_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000    40000.000000   
mean    1618.141050     58.241000     23.433000      5.443975        0.885900   
std      448.081153     30.169438     10.805273      3.750722        1.117928   
min      190.000000      0.000000      0.000000      0.000000        0.000000   
25%     1375.000000     39.000000     16.000000      2.000000        0.000000   
50%     1625.000000     53.000000     23.000000      6.000000        0.000000   
75%     1898.000000     71.000000     30.000000      9.000000        2.000000   
max     3347.000000    404.000000     77.000000     11.000000       10.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.265600         0.418950      0.433425      2.649150   
std        1.123382         0.493393      0.597392      3.807416   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      4.000000   
max        6.000000         1.000000      4.000000     30.000000   

       player2Kills  player3Kills  player4Kills  player5Kills     soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       5.158775      5.216625      5.184025      5.224425      5.072975   
std        4.012339      4.068957      4.041648      4.077852      3.331550   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      2.000000      3.000000   
50%        4.000000      4.000000      4.000000      4.000000      5.000000   
75%        7.000000      7.000000      7.000000      8.000000      7.000000   
max       34.000000     30.000000     30.000000     29.000000     25.000000   

           duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  
mean       9.387825      7.271150      3.441550      0.858100  
std        4.850135      4.227981      2.904857      1.350578  
min        0.000000      0.000000      0.000000      0.000000  
25%        6.000000      4.000000      1.000000      0.000000  
50%        9.000000      7.000000      3.000000      0.000000  
75%       12.000000     10.000000      5.000000      1.000000  
max       36.000000     27.000000     24.000000     14.000000

## 3.2. EUN Match Data Analysis

In [155]:
# Quick data frame with only select columns for statistical analysis
EUN_Stat = EUN_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [156]:
EUN_Stat.shape

(40000, 18)

In [157]:
EUN_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000    40000.000000   
mean    1594.112350     53.438700     23.726325      5.357350        0.869050   
std      432.684087     30.125272     11.049397      3.746619        1.091619   
min      190.000000      0.000000      0.000000      0.000000        0.000000   
25%     1347.000000     35.000000     16.000000      2.000000        0.000000   
50%     1594.500000     47.000000     23.000000      6.000000        0.000000   
75%     1861.000000     65.000000     31.000000      9.000000        1.000000   
max     3707.000000    477.000000     78.000000     11.000000       11.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.229075         0.371775      0.413825      2.672425   
std        1.113252         0.483285      0.588798      3.864349   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      4.000000   
max        6.000000         1.000000      4.000000     29.000000   

       player2Kills  player3Kills  player4Kills  player5Kills     soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       5.239250      5.277325      5.259400      5.277925      5.555200   
std        4.118165      4.150198      4.151824      4.161534      3.566577   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      2.000000      3.000000   
50%        4.000000      4.000000      4.000000      4.000000      5.000000   
75%        7.000000      8.000000      8.000000      8.000000      8.000000   
max       41.000000     33.000000     32.000000     30.000000     31.000000   

           duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  
mean       9.679650      7.014850      3.239200      0.830425  
std        4.993791      4.177788      2.866084      1.350098  
min        0.000000      0.000000      0.000000      0.000000  
25%        6.000000      4.000000      1.000000      0.000000  
50%        9.000000      7.000000      3.000000      0.000000  
75%       13.000000     10.000000      5.000000      1.000000  
max       39.000000     31.000000     20.000000     15.000000

## 3.3. EUW Match Data Analysis

In [158]:
# Quick data frame with only select columns for statistical analysis
EUW_Stat = EUW_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [159]:
EUW_Stat.shape

(40000, 18)

In [160]:
EUW_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000    40000.000000   
mean    1591.662600     57.823775     22.843525      5.383325        0.820825   
std      417.791747     29.750664     10.509165      3.629596        1.056645   
min      190.000000      0.000000      0.000000      0.000000        0.000000   
25%     1344.000000     39.000000     15.000000      2.000000        0.000000   
50%     1589.000000     52.000000     22.000000      5.000000        0.000000   
75%     1852.000000     70.000000     30.000000      9.000000        1.000000   
max     3828.000000    458.000000     82.000000     11.000000       11.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.162500         0.415350      0.419500      2.591825   
std        1.081676         0.492788      0.587689      3.718456   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      4.000000   
max        6.000000         1.000000      4.000000     38.000000   

       player2Kills  player3Kills  player4Kills  player5Kills     soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       5.020525      5.083225      5.061075      5.086875      4.817375   
std        3.948030      4.004035      3.977875      4.046188      3.296164   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      2.000000      2.000000   
50%        4.000000      4.000000      4.000000      4.000000      4.000000   
75%        7.000000      7.000000      7.000000      7.000000      7.000000   
max       29.000000     33.000000     30.000000     34.000000     29.000000   

           duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  
mean       9.196700      7.088575      3.358750      0.881450  
std        4.759567      4.129286      2.877813      1.389314  
min        0.000000      0.000000      0.000000      0.000000  
25%        6.000000      4.000000      1.000000      0.000000  
50%        9.000000      7.000000      3.000000      0.000000  
75%       12.000000     10.000000      5.000000      1.000000  
max       40.000000     29.000000     23.000000     18.000000

## 3.4. KR Match Data Analysis

In [161]:
# Quick data frame with only select columns for statistical analysis
KR_Stat = KR_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [162]:
KR_Stat.shape

(40000, 18)

In [163]:
KR_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count   40000.00000  40000.000000  40000.000000  40000.000000    40000.000000   
mean     1470.57765     59.047125     20.314100      4.590325        0.589350   
std       417.22998     30.461361      9.882362      3.451411        0.867315   
min       190.00000      0.000000      0.000000      0.000000        0.000000   
25%      1211.00000     38.000000     13.000000      1.000000        0.000000   
50%      1461.00000     54.000000     20.000000      4.000000        0.000000   
75%      1736.00000     73.000000     27.000000      8.000000        1.000000   
max      3424.00000    305.000000     79.000000     11.000000        8.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.011900         0.407925      0.353950      2.301600   
std        0.990875         0.491455      0.550751      3.388425   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      4.000000   
max        6.000000         1.000000      4.000000     30.000000   

       player2Kills  player3Kills  player4Kills  player5Kills     soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       4.489975      4.517050      4.477000      4.528475      3.857000   
std        3.663514      3.671219      3.647849      3.673354      2.750325   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      2.000000      2.000000   
50%        4.000000      4.000000      4.000000      4.000000      3.000000   
75%        6.000000      6.000000      6.000000      7.000000      5.000000   
max       30.000000     28.000000     28.000000     26.000000     23.000000   

          duoKills    trioKills     quadKills    pentaKills  
count  40000.00000  40000.00000  40000.000000  40000.000000  
mean       7.98130      6.46155      3.280150      0.960300  
std        4.33062      4.00154      2.952776      1.508768  
min        0.00000      0.00000      0.000000      0.000000  
25%        5.00000      3.00000      1.000000      0.000000  
50%        8.00000      6.00000      3.000000      0.000000  
75%       11.00000      9.00000      5.000000      1.000000  
max       31.00000     25.00000     22.000000     20.000000

## 3.5. LAN Match Data Analysis

In [164]:
# Quick data frame with only select columns for statistical analysis
LAN_Stat = LAN_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [165]:
LAN_Stat.shape

(40000, 18)

In [166]:
LAN_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000    40000.000000   
mean    1653.403800     57.425725     23.217925      5.484600        0.945550   
std      487.317244     32.611786     11.220382      3.871445        1.179394   
min      190.000000      0.000000      0.000000      0.000000        0.000000   
25%     1409.000000     38.000000     16.000000      2.000000        0.000000   
50%     1669.000000     51.000000     23.000000      6.000000        0.000000   
75%     1946.000000     70.000000     30.000000      9.000000        2.000000   
max     4429.000000    478.000000     82.000000     11.000000        8.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.333725         0.396350      0.409150      2.649200   
std        1.169845         0.489145      0.583956      3.867727   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      4.000000   
max        7.000000         1.000000      4.000000     36.000000   

       player2Kills  player3Kills  player4Kills  player5Kills     soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       5.154675      5.156500      5.130050      5.127500      5.095950   
std        4.136397      4.155044      4.155667      4.149099      3.493122   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      2.000000      3.000000   
50%        4.000000      4.000000      4.000000      4.000000      5.000000   
75%        7.000000      7.000000      7.000000      7.000000      7.000000   
max       32.000000     37.000000     33.000000     30.000000     32.000000   

           duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  
mean       9.193025      7.069225      3.492675      0.924825  
std        5.012439      4.262521      3.012594      1.430952  
min        0.000000      0.000000      0.000000      0.000000  
25%        6.000000      4.000000      1.000000      0.000000  
50%        9.000000      7.000000      3.000000      0.000000  
75%       12.000000     10.000000      5.000000      1.000000  
max       41.000000     28.000000     22.000000     15.000000

## 3.6. LAS Match Data Analysis

In [167]:
# Quick data frame with only select columns for statistical analysis
LAS_Stat = LAS_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [168]:
LAS_Stat.shape

(40000, 18)

In [169]:
LAS_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000    40000.000000   
mean    1652.859000     59.047650     22.821000      5.539575        0.931075   
std      467.336513     31.550559     10.756765      3.812984        1.154278   
min      190.000000      0.000000      0.000000      0.000000        0.000000   
25%     1408.000000     40.000000     15.000000      2.000000        0.000000   
50%     1665.000000     54.000000     23.000000      6.000000        0.000000   
75%     1939.000000     72.000000     30.000000      9.000000        2.000000   
max     3796.000000    350.000000     73.000000     11.000000       11.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.319275         0.409925      0.421000      2.596100   
std        1.158219         0.491826      0.588912      3.764687   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      4.000000   
max        6.000000         1.000000      4.000000     31.000000   

       player2Kills  player3Kills  player4Kills  player5Kills     soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       5.014550      5.056675      5.078700      5.074975      4.928650   
std        3.952882      4.032471      4.011871      4.040503      3.342961   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      2.000000      2.000000   
50%        4.000000      4.000000      4.000000      4.000000      4.000000   
75%        7.000000      7.000000      7.000000      7.000000      7.000000   
max       31.000000     30.000000     29.000000     33.000000     31.000000   

           duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  
mean       9.079075      6.988675      3.434475      0.910450  
std        4.829084      4.146224      2.921724      1.403453  
min        0.000000      0.000000      0.000000      0.000000  
25%        6.000000      4.000000      1.000000      0.000000  
50%        9.000000      7.000000      3.000000      0.000000  
75%       12.000000     10.000000      5.000000      1.000000  
max       33.000000     27.000000     22.000000     16.000000

## 3.7. NA Match Data Analysis

In [170]:
# Quick data frame with only select columns for statistical analysis
NA_Stat = NA_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [171]:
NA_Stat.shape

(40000, 18)

In [172]:
NA_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count   40000.00000  40000.000000  40000.000000  40000.000000    40000.000000   
mean     1592.48060     57.106575     22.348500      5.247275        0.808100   
std       412.15794     29.568040     10.208279      3.612244        1.051381   
min       190.00000      0.000000      0.000000      0.000000        0.000000   
25%      1341.00000     38.000000     15.000000      2.000000        0.000000   
50%      1580.00000     51.000000     22.000000      5.000000        0.000000   
75%      1846.00000     69.000000     29.000000      9.000000        1.000000   
max      4268.00000    439.000000     83.000000     11.000000        9.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.251725         0.418575      0.422750      2.545275   
std        1.107470         0.493332      0.590204      3.665950   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      4.000000   
max        6.000000         1.000000      4.000000     29.000000   

       player2Kills  player3Kills  player4Kills  player5Kills     soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       4.932150      4.964025      4.934025      4.973025      4.388275   
std        3.882393      3.903506      3.869541      3.876496      3.001440   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      2.000000      2.000000   
50%        4.000000      4.000000      4.000000      4.000000      4.000000   
75%        7.000000      7.000000      7.000000      7.000000      6.000000   
max       29.000000     32.000000     30.000000     30.000000     26.000000   

           duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  
mean       8.692800      7.074950      3.628775      1.021050  
std        4.494979      4.066853      3.000990      1.477096  
min        0.000000      0.000000      0.000000      0.000000  
25%        5.000000      4.000000      1.000000      0.000000  
50%        8.000000      7.000000      3.000000      0.000000  
75%       11.000000     10.000000      5.000000      2.000000  
max       33.000000     33.000000     22.000000     15.000000

## 3.8. OC Match Data Analysis

In [173]:
# Quick data frame with only select columns for statistical analysis
OC_Stat = OC_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [174]:
OC_Stat.shape

(40000, 18)

In [175]:
OC_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000    40000.000000   
mean    1687.589200     56.606425     24.800425      5.514400        0.934900   
std      439.208263     30.557681     11.175069      3.790053        1.172602   
min      190.000000      0.000000      0.000000      0.000000        0.000000   
25%     1423.000000     37.000000     17.000000      2.000000        0.000000   
50%     1679.000000     50.000000     24.000000      6.000000        0.000000   
75%     1958.000000     68.000000     32.000000      9.000000        2.000000   
max     3723.000000    477.000000     80.000000     11.000000        9.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.327150         0.357875      0.424600      2.802900   
std        1.158213         0.479381      0.595041      3.996943   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      5.000000   
max        6.000000         1.000000      4.000000     32.000000   

       player2Kills  player3Kills  player4Kills  player5Kills    soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.00000   
mean       5.478125      5.485250      5.509400      5.524750      5.70350   
std        4.263458      4.272796      4.265679      4.319468      3.67668   
min        0.000000      0.000000      0.000000      0.000000      0.00000   
25%        2.000000      2.000000      2.000000      2.000000      3.00000   
50%        5.000000      5.000000      5.000000      5.000000      5.00000   
75%        8.000000      8.000000      8.000000      8.000000      8.00000   
max       36.000000     34.000000     35.000000     31.000000     33.00000   

           duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  
mean       9.972200      7.335900      3.537100      0.934750  
std        5.103139      4.226691      2.988134      1.439772  
min        0.000000      0.000000      0.000000      0.000000  
25%        6.000000      4.000000      1.000000      0.000000  
50%       10.000000      7.000000      3.000000      0.000000  
75%       13.000000     10.000000      5.000000      1.000000  
max       34.000000     29.000000     23.000000     15.000000

## 3.9. RU Match Data Analysis

In [176]:
# Quick data frame with only select columns for statistical analysis
RU_Stat = RU_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [177]:
RU_Stat.shape

(40000, 18)

In [178]:
RU_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000    40000.000000   
mean    1621.530850     54.180000     25.429075      5.425725        0.892375   
std      446.291516     32.039049     11.821441      3.777121        1.113967   
min      191.000000      0.000000      0.000000      0.000000        0.000000   
25%     1372.000000     35.000000     17.000000      2.000000        0.000000   
50%     1625.000000     47.000000     25.000000      6.000000        0.000000   
75%     1890.000000     65.000000     33.000000      9.000000        2.000000   
max     3561.000000    434.000000     86.000000     11.000000       10.000000   

        dragonKills  riftHeraldKills   baronKills  player1Kills  player2Kills  \
count  40000.000000     40000.000000  40000.00000  40000.000000  40000.000000   
mean       1.259300         0.358800      0.39715      2.870025      5.605550   
std        1.132672         0.479654      0.57596      4.139935      4.386313   
min        0.000000         0.000000      0.00000      0.000000      0.000000   
25%        0.000000         0.000000      0.00000      0.000000      2.000000   
50%        1.000000         0.000000      0.00000      1.000000      5.000000   
75%        2.000000         1.000000      1.00000      5.000000      8.000000   
max        6.000000         1.000000      4.00000     34.000000     37.000000   

       player3Kills  player4Kills  player5Kills     soloKills      duoKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       5.674250      5.604975      5.674275      6.275600     10.588725   
std        4.481126      4.413328      4.466377      3.928623      5.443048   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      3.000000      7.000000   
50%        5.000000      5.000000      5.000000      6.000000     10.000000   
75%        8.000000      8.000000      8.000000      9.000000     14.000000   
max       35.000000     35.000000     38.000000     29.000000     39.000000   

          trioKills     quadKills   pentaKills  
count  40000.000000  40000.000000  40000.00000  
mean       7.310075      3.268775      0.78770  
std        4.357884      2.913125      1.29326  
min        0.000000      0.000000      0.00000  
25%        4.000000      1.000000      0.00000  
50%        7.000000      3.000000      0.00000  
75%       10.000000      5.000000      1.00000  
max       29.000000     23.000000     13.00000

## 3.10. TR Match Data Analysis

In [179]:
# Quick data frame with only select columns for statistical analysis
TR_Stat = TR_Clean[['gameDuration','wardsPlaced','teamKills','towerKills','inhibitorKills','dragonKills','riftHeraldKills','baronKills','player1Kills','player2Kills','player3Kills','player4Kills','player5Kills','soloKills','duoKills','trioKills','quadKills','pentaKills']]

In [180]:
TR_Stat.shape

(40000, 18)

In [181]:
TR_Stat.describe()

gameDuration   wardsPlaced     teamKills    towerKills  inhibitorKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000    40000.000000   
mean    1616.671650     51.040600     25.292725      5.400350        0.876300   
std      421.113684     27.178511     11.317881      3.740618        1.084563   
min      190.000000      0.000000      0.000000      0.000000        0.000000   
25%     1380.000000     34.000000     17.000000      2.000000        0.000000   
50%     1621.500000     46.000000     25.000000      6.000000        1.000000   
75%     1879.000000     62.000000     33.000000      9.000000        2.000000   
max     3373.000000    418.000000     85.000000     11.000000       10.000000   

        dragonKills  riftHeraldKills    baronKills  player1Kills  \
count  40000.000000     40000.000000  40000.000000  40000.000000   
mean       1.209850         0.371350      0.417750      2.859050   
std        1.102245         0.483172      0.587744      4.079203   
min        0.000000         0.000000      0.000000      0.000000   
25%        0.000000         0.000000      0.000000      0.000000   
50%        1.000000         0.000000      0.000000      1.000000   
75%        2.000000         1.000000      1.000000      5.000000   
max        6.000000         1.000000      4.000000     31.000000   

       player2Kills  player3Kills  player4Kills  player5Kills     soloKills  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       5.561400      5.617650      5.637400      5.617225      5.960225   
std        4.268341      4.310548      4.359013      4.344304      3.753278   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      2.000000      2.000000      2.000000      3.000000   
50%        5.000000      5.000000      5.000000      5.000000      5.000000   
75%        8.000000      8.000000      8.000000      8.000000      8.000000   
max       33.000000     35.000000     33.000000     32.000000     40.000000   

           duoKills     trioKills     quadKills    pentaKills  
count  40000.000000  40000.000000  40000.000000  40000.000000  
mean      10.395225      7.471250      3.414350      0.853375  
std        5.203489      4.273989      2.901866      1.346726  
min        0.000000      0.000000      0.000000      0.000000  
25%        7.000000      4.000000      1.000000      0.000000  
50%       10.000000      7.000000      3.000000      0.000000  
75%       14.000000     10.000000      5.000000      1.000000  
max       40.000000     31.000000     20.000000     14.000000

# 4. Exporting

In [182]:
BR_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataBR_Cleaned.csv'))
EUN_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataEUN_Cleaned.csv'))
EUW_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataEUW_Cleaned.csv'))
KR_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataKR_Cleaned.csv'))
LAN_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataLAN_Cleaned.csv'))
LAS_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataLAS_Cleaned.csv'))
NA_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataNA_Cleaned.csv'))
OC_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataOC_Cleaned.csv'))
RU_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataRU_Cleaned.csv'))
TR_Clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'MatchDataTR_Cleaned.csv'))